In [10]:
using Pkg
Pkg.activate("/media/mat/HDD/AdaptiveTransportMap/")

 Activating environment at `/media/mat/HDD/AdaptiveTransportMap/Project.toml`


In [11]:
using Revise
using AdaptiveTransportMap
using LinearAlgebra
import LinearAlgebra: ldiv!, dot
using Test
using ForwardDiff
using SpecialFunctions
using BenchmarkTools
using TransportMap
using QuadGK
using Polynomials
using Distributions
using Random
using LoopVectorization
using Optim
using NLsolve
using MLDataUtils
using MLDataPattern
using Test
using SparseArrays
using QRupdate
using AdaptiveTransportMap: vander, transform!, evaluate, ncoeff, optimize, negative_log_likelihood!, derivative

# using Profile
# using ProfileView

### 1D example

In [361]:
Nx = 3
Ne = 500
ens = EnsembleState(Nx, Ne)
ens.S .= randn(Nx, Ne)

B = MultiBasis(CstProHermite(3), Nx)

# idx = [0 0 0; 2 0 1; 0 1 0; 0 2 1; 0 1 2; 1 0 0; 2 2 2]
idx = [0 0 0]; #2 0 1; 0 1 0; 0 2 1; 0 1 2; 1 0 0; 2 2 2]

# truncidx = idx[1:2:end,:]

coeff =  randn(size(idx,1))

f = ExpandedFunction(B, idx, coeff)

ExpandedFunction(5, 1, 3, MultiBasis(Basis of 5 functions: Constant -> 3th degree Probabilistic Hermite function
, 3), [0 0 0], [0.27538278274373806])

In [362]:
ForwardDiff.hessian(xi ->ForwardDiff.gradient(f, xi)[3], member(ens,1))

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [363]:
H = hess_x_grad_xd(f, ens.S, f.idx);
size(H)

(500, 3, 3)

In [364]:
H[1,:,:] 

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [357]:
H[1,1,1]

-0.025978756653024657

In [358]:
H[1,1,3]

-0.04920913520740215

In [359]:
H[1,3,1]

-0.04920913520740215

In [360]:
# Verify hess_x_grad_xd
dxidxjdxkψ = hess_x_grad_xd(f, ens.S, f.idx)

for i=1:Ne
    dxidxjdxkψ_t = ForwardDiff.hessian(xi ->ForwardDiff.gradient(f, xi)[3], member(ens,i))
    @test norm(dxidxjdxkψ[i,:,:] - dxidxjdxkψ_t)<1e-10
end

In [366]:
using AdaptiveTransportMap: evaluate


@testset "Test evaluation, gradient and hessian of expanded function Nx = 1 I" begin

    Nx = 1
    Ne = 500
    ens = EnsembleState(Nx, Ne)
    ens.S .= randn(Nx, Ne)


    B = MultiBasis(CstProHermite(3), Nx)

    idx = reshape([0], (1, 1))
    truncidx = idx[1:2:end,:]

    coeff =  randn(size(idx,1))

    f = ExpandedFunction(B, idx, coeff)



    ψt_basis, dψt_basis, d2ψt_basis = alleval(f, ens)

    ψ_basis = evaluate_basis(f, ens.S)
    dψ_basis = grad_x_basis(f, ens.S)
    d2ψ_basis = hess_x_basis(f, ens.S);
    @test norm(ψt_basis - ψ_basis)<1e-8
    @test norm(dψt_basis - dψ_basis)<1e-8
    @test norm(d2ψt_basis - d2ψ_basis)<1e-8


    # For truncated basis
    ψtrunc_basis = evaluate_basis(f, ens.S, truncidx)
    dψtrunc_basis = grad_x_basis(f, ens.S, truncidx)
    d2ψtrunc_basis = hess_x_basis(f, ens.S, truncidx);

    @test norm(ψ_basis[:,1:2:end] - ψtrunc_basis)<1e-8
    @test norm(dψ_basis[:,1:2:end,:] - dψtrunc_basis)<1e-8
    @test norm(d2ψt_basis[:,1:2:end,:,:] - d2ψtrunc_basis)<1e-8


    # Verify function evaluation
    @test norm(map(i->f(member(ens,i)),1:Ne) - evaluate(f, ens.S))<1e-8

    #  Verify gradient
    dψ = grad_x(f, ens.S)
    @test norm(hcat(map(i->ForwardDiff.gradient(f, member(ens,i)), 1:Ne)...)' - dψ)<1e-8

    # Verify hessian
    d2ψ = hess_x(f, ens.S)

    for i=1:Ne
        d2ψt = ForwardDiff.hessian(f, member(ens,i))
        @test norm(d2ψt - d2ψ[i,:,:])<1e-8
    end


    # Verify grad_xd
    dψxd = grad_xd(f, ens.S)

    for i=1:Ne
        dψxd_t = ForwardDiff.gradient(f, member(ens,i))[end]
        @test abs(dψxd[i] - dψxd_t)<1e-10
    end

    # Verify hess_xd
    d2ψxd = hess_xd(f, ens.S)

    for i=1:Ne
        d2ψxd_t = ForwardDiff.hessian(f, member(ens,i))[end,end]
        @test abs(d2ψxd[i] - d2ψxd_t)<1e-10
    end

    # Verify grad_x_grad_xd
    dxdxkψ = grad_x_grad_xd(f, ens.S)

    for i=1:Ne
        dxdxkψ_t = ForwardDiff.hessian(f, member(ens,i))
        for j=1:Nx
            @test abs(dxdxkψ[i,j] - dxdxkψ_t[j,end])<1e-10
        end
    end

    # Verify hess_x_grad_xd
    dxidxjdxkψ = hess_x_grad_xd(f, ens.S, f.idx)

    for i=1:Ne
        dxidxjdxkψ_t = ForwardDiff.hessian(xi ->ForwardDiff.gradient(f, xi)[Nx], member(ens,i))
        @test norm(dxidxjdxkψ[i,:,:] - dxidxjdxkψ_t)<1e-10
    end

    # Verify grad_coeff
    dψcoeff  = grad_coeff(f, ens.S)
    dψcoefftrunc  = grad_coeff(f, ens.S, collect(1:2:size(idx,1)))
    @test norm(dψcoeff[:,1:2:end] - dψcoefftrunc)<1e-10

    @test norm(dψcoeff - ψ_basis)<1e-10
    @test norm(dψcoefftrunc - ψtrunc_basis)<1e-10

    # Verify hess_coeff
    d2ψcoeff  = hess_coeff(f, ens.S)
    d2ψcoefftrunc  = hess_coeff(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeff)<1e-10

    # Verify grad_coeff_grad_xd
    dψcoeffxd = grad_coeff_grad_xd(f, ens.S)
    dψcoeffxdtrunc = grad_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(dψcoeffxd[:,1:2:end] - dψcoeffxdtrunc)<1e-10
    @test norm(dψcoeffxd - grad_xk_basis(f, ens.S, 1, Nx))<1e-10
    @test norm(dψcoeffxdtrunc - grad_xk_basis(f, ens.S, 1, Nx, f.idx[collect(1:2:size(idx,1)),:]))<1e-10

    # Verify hess_coeff_grad_xd
    d2ψcoeffxd = hess_coeff_grad_xd(f, ens.S)
    d2ψcoeffxdtrunc = hess_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeffxd)<1e-10
    @test norm(d2ψcoeffxdtrunc)<1e-10
end

@testset "Test evaluation, gradient and hessian of expanded function Nx = 1 II" begin

    Nx = 1
    Ne = 500
    ens = EnsembleState(Nx, Ne)
    ens.S .= randn(Nx, Ne)


    B = MultiBasis(CstProHermite(3), Nx)

    idx = reshape([0; 1; 2; 3], (4, 1))
    truncidx = idx[1:2:end,:]

    coeff =  randn(size(idx,1))

    f = ExpandedFunction(B, idx, coeff)



    ψt_basis, dψt_basis, d2ψt_basis = alleval(f, ens)

    ψ_basis = evaluate_basis(f, ens.S)
    dψ_basis = grad_x_basis(f, ens.S)
    d2ψ_basis = hess_x_basis(f, ens.S);
    @test norm(ψt_basis - ψ_basis)<1e-8
    @test norm(dψt_basis - dψ_basis)<1e-8
    @test norm(d2ψt_basis - d2ψ_basis)<1e-8


    # For truncated basis
    ψtrunc_basis = evaluate_basis(f, ens.S, truncidx)
    dψtrunc_basis = grad_x_basis(f, ens.S, truncidx)
    d2ψtrunc_basis = hess_x_basis(f, ens.S, truncidx);

    @test norm(ψ_basis[:,1:2:end] - ψtrunc_basis)<1e-8
    @test norm(dψ_basis[:,1:2:end,:] - dψtrunc_basis)<1e-8
    @test norm(d2ψt_basis[:,1:2:end,:,:] - d2ψtrunc_basis)<1e-8


    # Verify function evaluation
    @test norm(map(i->f(member(ens,i)),1:Ne) - evaluate(f, ens.S))<1e-8

    #  Verify gradient
    dψ = grad_x(f, ens.S)
    @test norm(hcat(map(i->ForwardDiff.gradient(f, member(ens,i)), 1:Ne)...)' - dψ)<1e-8

    # Verify hessian
    d2ψ = hess_x(f, ens.S)

    for i=1:Ne
        d2ψt = ForwardDiff.hessian(f, member(ens,i))
        @test norm(d2ψt - d2ψ[i,:,:])<1e-8
    end


    # Verify grad_xd
    dψxd = grad_xd(f, ens.S)

    for i=1:Ne
        dψxd_t = ForwardDiff.gradient(f, member(ens,i))[end]
        @test abs(dψxd[i] - dψxd_t)<1e-10
    end

    # Verify hess_xd
    d2ψxd = hess_xd(f, ens.S)

    for i=1:Ne
        d2ψxd_t = ForwardDiff.hessian(f, member(ens,i))[end,end]
        @test abs(d2ψxd[i] - d2ψxd_t)<1e-10
    end

    # Verify grad_x_grad_xd
    dxdxkψ = grad_x_grad_xd(f, ens.S)

    for i=1:Ne
        dxdxkψ_t = ForwardDiff.hessian(f, member(ens,i))
        for j=1:Nx
            @test abs(dxdxkψ[i,j] - dxdxkψ_t[j,end])<1e-10
        end
    end

    # Verify hess_x_grad_xd
    dxidxjdxkψ = hess_x_grad_xd(f, ens.S, f.idx)

    for i=1:Ne
        dxidxjdxkψ_t = ForwardDiff.hessian(xi ->ForwardDiff.gradient(f, xi)[Nx], member(ens,i))
        @test norm(dxidxjdxkψ[i,:,:] - dxidxjdxkψ_t)<1e-10
    end

    # Verify grad_coeff
    dψcoeff  = grad_coeff(f, ens.S)
    dψcoefftrunc  = grad_coeff(f, ens.S, collect(1:2:size(idx,1)))
    @test norm(dψcoeff[:,1:2:end] - dψcoefftrunc)<1e-10

    @test norm(dψcoeff - ψ_basis)<1e-10
    @test norm(dψcoefftrunc - ψtrunc_basis)<1e-10

    # Verify hess_coeff
    d2ψcoeff  = hess_coeff(f, ens.S)
    d2ψcoefftrunc  = hess_coeff(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeff)<1e-10

    # Verify grad_coeff_grad_xd
    dψcoeffxd = grad_coeff_grad_xd(f, ens.S)
    dψcoeffxdtrunc = grad_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(dψcoeffxd[:,1:2:end] - dψcoeffxdtrunc)<1e-10
    @test norm(dψcoeffxd - grad_xk_basis(f, ens.S, 1, Nx))<1e-10
    @test norm(dψcoeffxdtrunc - grad_xk_basis(f, ens.S, 1, Nx, f.idx[collect(1:2:size(idx,1)),:]))<1e-10

    # Verify hess_coeff_grad_xd
    d2ψcoeffxd = hess_coeff_grad_xd(f, ens.S)
    d2ψcoeffxdtrunc = hess_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeffxd)<1e-10
    @test norm(d2ψcoeffxdtrunc)<1e-10
end

@testset "Test evaluation, gradient and hessian of expanded function Nx = 2" begin

    Nx = 2
    Ne = 500
    ens = EnsembleState(Nx, Ne)
    ens.S .= randn(Nx, Ne)


    B = MultiBasis(CstProHermite(3), Nx)

    idx = [0 0]
    truncidx = idx[1:2:end,:]

    coeff =  randn(size(idx,1))

    f = ExpandedFunction(B, idx, coeff)


    ψt_basis, dψt_basis, d2ψt_basis = alleval(f, ens)

    ψ_basis = evaluate_basis(f, ens.S)
    dψ_basis = grad_x_basis(f, ens.S)
    d2ψ_basis = hess_x_basis(f, ens.S);
    @test norm(ψt_basis - ψ_basis)<1e-8
    @test norm(dψt_basis - dψ_basis)<1e-8
    @test norm(d2ψt_basis - d2ψ_basis)<1e-8


    # For truncated basis
    ψtrunc_basis = evaluate_basis(f, ens.S, truncidx)
    dψtrunc_basis = grad_x_basis(f, ens.S, truncidx)
    d2ψtrunc_basis = hess_x_basis(f, ens.S, truncidx);

    @test norm(ψ_basis[:,1:2:end] - ψtrunc_basis)<1e-8
    @test norm(dψ_basis[:,1:2:end,:] - dψtrunc_basis)<1e-8
    @test norm(d2ψt_basis[:,1:2:end,:,:] - d2ψtrunc_basis)<1e-8


    # Verify function evaluation
    @test norm(map(i->f(member(ens,i)),1:Ne) - evaluate(f, ens.S))<1e-8

    #  Verify gradient
    dψ = grad_x(f, ens.S)
    @test norm(hcat(map(i->ForwardDiff.gradient(f, member(ens,i)), 1:Ne)...)' - dψ)<1e-8

    # Verify hessian
    d2ψ = hess_x(f, ens.S)

    for i=1:Ne
        d2ψt = ForwardDiff.hessian(f, member(ens,i))
        @test norm(d2ψt - d2ψ[i,:,:])<1e-8
    end


    # Verify grad_xd
    dψxd = grad_xd(f, ens.S)

    for i=1:Ne
        dψxd_t = ForwardDiff.gradient(f, member(ens,i))[end]
        @test abs(dψxd[i] - dψxd_t)<1e-10
    end

    # Verify hess_xd
    d2ψxd = hess_xd(f, ens.S)

    for i=1:Ne
        d2ψxd_t = ForwardDiff.hessian(f, member(ens,i))[end,end]
        @test abs(d2ψxd[i] - d2ψxd_t)<1e-10
    end

    # Verify grad_x_grad_xd
    dxdxkψ = grad_x_grad_xd(f, ens.S)

    for i=1:Ne
        dxdxkψ_t = ForwardDiff.hessian(f, member(ens,i))
        for j=1:Nx
            @test abs(dxdxkψ[i,j] - dxdxkψ_t[j,end])<1e-10
        end
    end

    # Verify hess_x_grad_xd
    dxidxjdxkψ = hess_x_grad_xd(f, ens.S, f.idx)

    for i=1:Ne
        dxidxjdxkψ_t = ForwardDiff.hessian(xi ->ForwardDiff.gradient(f, xi)[3], member(ens,i))
        @test norm(dxidxjdxkψ[i,:,:] - dxidxjdxkψ_t)<1e-10
    end

    # Verify grad_coeff
    dψcoeff  = grad_coeff(f, ens.S)
    dψcoefftrunc  = grad_coeff(f, ens.S, collect(1:2:size(idx,1)))
    @test norm(dψcoeff[:,1:2:end] - dψcoefftrunc)<1e-10

    @test norm(dψcoeff - ψ_basis)<1e-10
    @test norm(dψcoefftrunc - ψtrunc_basis)<1e-10

    # Verify hess_coeff
    d2ψcoeff  = hess_coeff(f, ens.S)
    d2ψcoefftrunc  = hess_coeff(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeff)<1e-10

    # Verify grad_coeff_grad_xd
    dψcoeffxd = grad_coeff_grad_xd(f, ens.S)
    dψcoeffxdtrunc = grad_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(dψcoeffxd[:,1:2:end] - dψcoeffxdtrunc)<1e-10
    @test norm(dψcoeffxd - grad_xk_basis(f, ens.S, 1, Nx))<1e-10
    @test norm(dψcoeffxdtrunc - grad_xk_basis(f, ens.S, 1, Nx, f.idx[collect(1:2:size(idx,1)),:]))<1e-10

    # Verify hess_coeff_grad_xd
    d2ψcoeffxd = hess_coeff_grad_xd(f, ens.S)
    d2ψcoeffxdtrunc = hess_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeffxd)<1e-10
    @test norm(d2ψcoeffxdtrunc)<1e-10
end

@testset "Test evaluation, gradient and hessian of expanded function Nx = 2" begin

    Nx = 2
    Ne = 500
    ens = EnsembleState(Nx, Ne)
    ens.S .= randn(Nx, Ne)


    B = MultiBasis(CstProHermite(3), Nx)

    idx = [0 0; 0 1; 1 0; 1 1; 1 2]
    truncidx = idx[1:2:end,:]

    coeff =  randn(size(idx,1))

    f = ExpandedFunction(B, idx, coeff)



    ψt_basis, dψt_basis, d2ψt_basis = alleval(f, ens)

    ψ_basis = evaluate_basis(f, ens.S)
    dψ_basis = grad_x_basis(f, ens.S)
    d2ψ_basis = hess_x_basis(f, ens.S);
    @test norm(ψt_basis - ψ_basis)<1e-8
    @test norm(dψt_basis - dψ_basis)<1e-8
    @test norm(d2ψt_basis - d2ψ_basis)<1e-8


    # For truncated basis
    ψtrunc_basis = evaluate_basis(f, ens.S, truncidx)
    dψtrunc_basis = grad_x_basis(f, ens.S, truncidx)
    d2ψtrunc_basis = hess_x_basis(f, ens.S, truncidx);

    @test norm(ψ_basis[:,1:2:end] - ψtrunc_basis)<1e-8
    @test norm(dψ_basis[:,1:2:end,:] - dψtrunc_basis)<1e-8
    @test norm(d2ψt_basis[:,1:2:end,:,:] - d2ψtrunc_basis)<1e-8


    # Verify function evaluation
    @test norm(map(i->f(member(ens,i)),1:Ne) - evaluate(f, ens.S))<1e-8

    #  Verify gradient
    dψ = grad_x(f, ens.S)
    @test norm(hcat(map(i->ForwardDiff.gradient(f, member(ens,i)), 1:Ne)...)' - dψ)<1e-8

    # Verify hessian
    d2ψ = hess_x(f, ens.S)

    for i=1:Ne
        d2ψt = ForwardDiff.hessian(f, member(ens,i))
        @test norm(d2ψt - d2ψ[i,:,:])<1e-8
    end


    # Verify grad_xd
    dψxd = grad_xd(f, ens.S)

    for i=1:Ne
        dψxd_t = ForwardDiff.gradient(f, member(ens,i))[end]
        @test abs(dψxd[i] - dψxd_t)<1e-10
    end

    # Verify hess_xd
    d2ψxd = hess_xd(f, ens.S)

    for i=1:Ne
        d2ψxd_t = ForwardDiff.hessian(f, member(ens,i))[end,end]
        @test abs(d2ψxd[i] - d2ψxd_t)<1e-10
    end

    # Verify grad_x_grad_xd
    dxdxkψ = grad_x_grad_xd(f, ens.S)

    for i=1:Ne
        dxdxkψ_t = ForwardDiff.hessian(f, member(ens,i))
        for j=1:Nx
            @test abs(dxdxkψ[i,j] - dxdxkψ_t[j,end])<1e-10
        end
    end

    # Verify hess_x_grad_xd
    dxidxjdxkψ = hess_x_grad_xd(f, ens.S, f.idx)

    for i=1:Ne
        dxidxjdxkψ_t = ForwardDiff.hessian(xi ->ForwardDiff.gradient(f, xi)[3], member(ens,i))
        @test norm(dxidxjdxkψ[i,:,:] - dxidxjdxkψ_t)<1e-10
    end

    # Verify grad_coeff
    dψcoeff  = grad_coeff(f, ens.S)
    dψcoefftrunc  = grad_coeff(f, ens.S, collect(1:2:size(idx,1)))
    @test norm(dψcoeff[:,1:2:end] - dψcoefftrunc)<1e-10

    @test norm(dψcoeff - ψ_basis)<1e-10
    @test norm(dψcoefftrunc - ψtrunc_basis)<1e-10

    # Verify hess_coeff
    d2ψcoeff  = hess_coeff(f, ens.S)
    d2ψcoefftrunc  = hess_coeff(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeff)<1e-10

    # Verify grad_coeff_grad_xd
    dψcoeffxd = grad_coeff_grad_xd(f, ens.S)
    dψcoeffxdtrunc = grad_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(dψcoeffxd[:,1:2:end] - dψcoeffxdtrunc)<1e-10
    @test norm(dψcoeffxd - grad_xk_basis(f, ens.S, 1, Nx))<1e-10
    @test norm(dψcoeffxdtrunc - grad_xk_basis(f, ens.S, 1, Nx, f.idx[collect(1:2:size(idx,1)),:]))<1e-10

    # Verify hess_coeff_grad_xd
    d2ψcoeffxd = hess_coeff_grad_xd(f, ens.S)
    d2ψcoeffxdtrunc = hess_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeffxd)<1e-10
    @test norm(d2ψcoeffxdtrunc)<1e-10
end

@testset "Test evaluation, gradient and hessian of expanded function Nx = 3 I" begin

    Nx = 3
    Ne = 500
    ens = EnsembleState(Nx, Ne)
    ens.S .= randn(Nx, Ne)

    B = MultiBasis(CstProHermite(3), Nx)

    idx = [0 0 0; 2 0 1; 0 1 0; 0 2 1; 0 1 2; 1 0 0; 2 2 2]
    truncidx = idx[1:2:end,:]
    coeff =  randn(size(idx,1))

    f = ExpandedFunction(B, idx, coeff)

    ψt_basis, dψt_basis, d2ψt_basis = alleval(f, ens)

    ψ_basis = evaluate_basis(f, ens.S)
    dψ_basis = grad_x_basis(f, ens.S)
    d2ψ_basis = hess_x_basis(f, ens.S);
    @test norm(ψt_basis - ψ_basis)<1e-8
    @test norm(dψt_basis - dψ_basis)<1e-8
    @test norm(d2ψt_basis - d2ψ_basis)<1e-8


    # For truncated basis
    ψtrunc_basis = evaluate_basis(f, ens.S, truncidx)
    dψtrunc_basis = grad_x_basis(f, ens.S, truncidx)
    d2ψtrunc_basis = hess_x_basis(f, ens.S, truncidx);

    @test norm(ψ_basis[:,1:2:end] - ψtrunc_basis)<1e-8
    @test norm(dψ_basis[:,1:2:end,:] - dψtrunc_basis)<1e-8
    @test norm(d2ψt_basis[:,1:2:end,:,:] - d2ψtrunc_basis)<1e-8


    # Verify function evaluation
    @test norm(map(i->f(member(ens,i)),1:Ne) - evaluate(f, ens.S))<1e-8

    #  Verify gradient
    dψ = grad_x(f, ens.S)
    @test norm(hcat(map(i->ForwardDiff.gradient(f, member(ens,i)), 1:Ne)...)' - dψ)<1e-8

    # Verify hessian
    d2ψ = hess_x(f, ens.S)

    for i=1:Ne
        d2ψt = ForwardDiff.hessian(f, member(ens,i))
        @test norm(d2ψt - d2ψ[i,:,:])<1e-8
    end


    # Verify grad_xd
    dψxd = grad_xd(f, ens.S)

    for i=1:Ne
        dψxd_t = ForwardDiff.gradient(f, member(ens,i))[end]
        @test abs(dψxd[i] - dψxd_t)<1e-10
    end

    # Verify hess_xd
    d2ψxd = hess_xd(f, ens.S)

    for i=1:Ne
        d2ψxd_t = ForwardDiff.hessian(f, member(ens,i))[end,end]
        @test abs(d2ψxd[i] - d2ψxd_t)<1e-10
    end

    # Verify grad_x_grad_xd
    dxdxkψ = grad_x_grad_xd(f, ens.S)

    for i=1:Ne
        dxdxkψ_t = ForwardDiff.hessian(f, member(ens,i))
        for j=1:Nx
            @test abs(dxdxkψ[i,j] - dxdxkψ_t[j,end])<1e-10
        end
    end

    # Verify hess_x_grad_xd
    dxidxjdxkψ = hess_x_grad_xd(f, ens.S, f.idx)

    for i=1:Ne
        dxidxjdxkψ_t = ForwardDiff.hessian(xi ->ForwardDiff.gradient(f, xi)[3], member(ens,i))
        @test norm(dxidxjdxkψ[i,:,:] - dxidxjdxkψ_t)<1e-10
    end

    # Verify grad_coeff
    dψcoeff  = grad_coeff(f, ens.S)
    dψcoefftrunc  = grad_coeff(f, ens.S, collect(1:2:size(idx,1)))
    @test norm(dψcoeff[:,1:2:end] - dψcoefftrunc)<1e-10

    @test norm(dψcoeff - ψ_basis)<1e-10
    @test norm(dψcoefftrunc - ψtrunc_basis)<1e-10

    # Verify hess_coeff
    d2ψcoeff  = hess_coeff(f, ens.S)
    d2ψcoefftrunc  = hess_coeff(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeff)<1e-10

    # Verify grad_coeff_grad_xd
    dψcoeffxd = grad_coeff_grad_xd(f, ens.S)
    dψcoeffxdtrunc = grad_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(dψcoeffxd[:,1:2:end] - dψcoeffxdtrunc)<1e-10
    @test norm(dψcoeffxd - grad_xk_basis(f, ens.S, 1, Nx))<1e-10
    @test norm(dψcoeffxdtrunc - grad_xk_basis(f, ens.S, 1, Nx, f.idx[collect(1:2:size(idx,1)),:]))<1e-10

    # Verify hess_coeff_grad_xd
    d2ψcoeffxd = hess_coeff_grad_xd(f, ens.S)
    d2ψcoeffxdtrunc = hess_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeffxd)<1e-10
    @test norm(d2ψcoeffxdtrunc)<1e-10
end

@testset "Test evaluation, gradient and hessian of expanded function Nx = 3 II" begin

    Nx = 3
    Ne = 500
    ens = EnsembleState(Nx, Ne)
    ens.S .= randn(Nx, Ne)

    B = MultiBasis(CstProHermite(3), Nx)

    idx = [0 0 0]
    truncidx = idx[1:2:end,:]
    coeff =  randn(size(idx,1))

    f = ExpandedFunction(B, idx, coeff)

    ψt_basis, dψt_basis, d2ψt_basis = alleval(f, ens)

    ψ_basis = evaluate_basis(f, ens.S)
    dψ_basis = grad_x_basis(f, ens.S)
    d2ψ_basis = hess_x_basis(f, ens.S);
    @test norm(ψt_basis - ψ_basis)<1e-8
    @test norm(dψt_basis - dψ_basis)<1e-8
    @test norm(d2ψt_basis - d2ψ_basis)<1e-8


    # For truncated basis
    ψtrunc_basis = evaluate_basis(f, ens.S, truncidx)
    dψtrunc_basis = grad_x_basis(f, ens.S, truncidx)
    d2ψtrunc_basis = hess_x_basis(f, ens.S, truncidx);

    @test norm(ψ_basis[:,1:2:end] - ψtrunc_basis)<1e-8
    @test norm(dψ_basis[:,1:2:end,:] - dψtrunc_basis)<1e-8
    @test norm(d2ψt_basis[:,1:2:end,:,:] - d2ψtrunc_basis)<1e-8


    # Verify function evaluation
    @test norm(map(i->f(member(ens,i)),1:Ne) - evaluate(f, ens.S))<1e-8

    #  Verify gradient
    dψ = grad_x(f, ens.S)
    @test norm(hcat(map(i->ForwardDiff.gradient(f, member(ens,i)), 1:Ne)...)' - dψ)<1e-8

    # Verify hessian
    d2ψ = hess_x(f, ens.S)

    for i=1:Ne
        d2ψt = ForwardDiff.hessian(f, member(ens,i))
        @test norm(d2ψt - d2ψ[i,:,:])<1e-8
    end


    # Verify grad_xd
    dψxd = grad_xd(f, ens.S)

    for i=1:Ne
        dψxd_t = ForwardDiff.gradient(f, member(ens,i))[end]
        @test abs(dψxd[i] - dψxd_t)<1e-10
    end

    # Verify hess_xd
    d2ψxd = hess_xd(f, ens.S)

    for i=1:Ne
        d2ψxd_t = ForwardDiff.hessian(f, member(ens,i))[end,end]
        @test abs(d2ψxd[i] - d2ψxd_t)<1e-10
    end

    # Verify grad_x_grad_xd
    dxdxkψ = grad_x_grad_xd(f, ens.S)

    for i=1:Ne
        dxdxkψ_t = ForwardDiff.hessian(f, member(ens,i))
        for j=1:Nx
            @test abs(dxdxkψ[i,j] - dxdxkψ_t[j,end])<1e-10
        end
    end

    # Verify hess_x_grad_xd
    dxidxjdxkψ = hess_x_grad_xd(f, ens.S, f.idx)

    for i=1:Ne
        dxidxjdxkψ_t = ForwardDiff.hessian(xi ->ForwardDiff.gradient(f, xi)[Nx], member(ens,i))
        @test norm(dxidxjdxkψ[i,:,:] - dxidxjdxkψ_t)<1e-10
    end

    # Verify grad_coeff
    dψcoeff  = grad_coeff(f, ens.S)
    dψcoefftrunc  = grad_coeff(f, ens.S, collect(1:2:size(idx,1)))
    @test norm(dψcoeff[:,1:2:end] - dψcoefftrunc)<1e-10

    @test norm(dψcoeff - ψ_basis)<1e-10
    @test norm(dψcoefftrunc - ψtrunc_basis)<1e-10

    # Verify hess_coeff
    d2ψcoeff  = hess_coeff(f, ens.S)
    d2ψcoefftrunc  = hess_coeff(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeff)<1e-10

    # Verify grad_coeff_grad_xd
    dψcoeffxd = grad_coeff_grad_xd(f, ens.S)
    dψcoeffxdtrunc = grad_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(dψcoeffxd[:,1:2:end] - dψcoeffxdtrunc)<1e-10
    @test norm(dψcoeffxd - grad_xk_basis(f, ens.S, 1, Nx))<1e-10
    @test norm(dψcoeffxdtrunc - grad_xk_basis(f, ens.S, 1, Nx, f.idx[collect(1:2:size(idx,1)),:]))<1e-10

    # Verify hess_coeff_grad_xd
    d2ψcoeffxd = hess_coeff_grad_xd(f, ens.S)
    d2ψcoeffxdtrunc = hess_coeff_grad_xd(f, ens.S, collect(1:2:size(idx,1)))

    @test norm(d2ψcoeffxd)<1e-10
    @test norm(d2ψcoeffxdtrunc)<1e-10
end

Test evaluation, gradient and hessian of expanded function Nx = 1 I: Error During Test at In[366]:4
  Got exception outside of a @test
  BoundsError: attempt to access 1-element Array{Float64,1} at index [3]
  Stacktrace:
   [1] getindex(::Array{Float64,1}, ::Int64) at ./array.jl:809
   [2] (::var"#225#228"{ExpandedFunction})(::Array{ForwardDiff.Dual{ForwardDiff.Tag{var"#225#228"{ExpandedFunction},Float64},ForwardDiff.Dual{ForwardDiff.Tag{var"#225#228"{ExpandedFunction},Float64},Float64,1},1},1}) at ./In[366]:89
   [3] vector_mode_dual_eval at /home/mat/.julia/packages/ForwardDiff/sdToQ/src/apiutils.jl:37 [inlined]
   [4] vector_mode_gradient(::var"#225#228"{ExpandedFunction}, ::Array{ForwardDiff.Dual{ForwardDiff.Tag{var"#225#228"{ExpandedFunction},Float64},Float64,1},1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{var"#225#228"{ExpandedFunction},Float64},ForwardDiff.Dual{ForwardDiff.Tag{var"#225#228"{ExpandedFunction},Float64},Float64,1},1,Array{ForwardDiff.Dual{ForwardDiff.Tag{var"#

LoadError: Some tests did not pass: 2008 passed, 0 failed, 1 errored, 0 broken.

### Test Hessian of the log π(x)

In [30]:
Nx = 2
Ne = 8
m = 10

X = randn(Nx, Ne)

idx = [0 0; 0 1; 1 0; 1 1; 1 2]
coeff =   [0.6285037650645056;
 -0.4744029092496623;
  1.1405280011620331;
 -0.7217760771894809;
  0.11855056306742319];

C = MapComponent(m, Nx, idx, coeff);

In [34]:
dψ_basis = grad_x_basis(C.I.f.f, X)

8×5×2 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  -0.207296    -0.130929     0.00117735
 0.0  0.0  -0.216523    -0.134105     0.0375507
 0.0  0.0   0.00618292   0.00360034   0.00205305
 0.0  0.0  -0.199714    -0.0830991   -0.107373
 0.0  0.0   0.209274     0.0991538   -0.106331
 0.0  0.0  -0.236677    -0.10036     -0.126702
 0.0  0.0  -0.270316    -0.120917     0.142049
 0.0  0.0  -0.0785179   -0.0495593    0.00259814

[:, :, 2] =
 0.0   0.00283979  0.0   0.00155384  0.345581
 0.0   0.0867129   0.0   0.0465448   0.31942
 0.0  -0.166026    0.0  -0.104855    0.307967
 0.0  -0.268816    0.0  -0.149159    0.0381479
 0.0   0.254048    0.0   0.138466    0.109751
 0.0  -0.26767     0.0  -0.064575    0.0207737
 0.0   0.262746    0.0   0.0959916   0.0506544
 0.0   0.0165449   0.0   0.0102847   0.391819

In [41]:
dxlogDJ = zeros(Ne, Nx)

ψoffdψxd = grad_xd(C.I.f.f, X)

8-element Array{Float64,1}:
  0.03850011681624252
 -0.036864339594153354
  0.19095459274793916
  0.23970874743411022
 -0.20745155095311177
  0.17605463803346075
 -0.18792702339659972
  0.03117818085903034

In [50]:
grad_x_grad_xd(C.I.f.f, X, C.I.f.f.idx)

8×2 Array{Float64,2}:
 -0.0150962    0.275081
 -0.00172344   0.272766
  0.00109835   0.191537
 -0.0403773   -0.00821251
 -0.0333779    0.127178
 -0.0481415    0.0110568
  0.0468207    0.0774556
 -0.00492957   0.294571

In [51]:
hess_xd(C.I.f.f, X)

8-element Array{Float64,1}:
  0.27508054698884865
  0.2727658334063561
  0.19153741860252596
 -0.008212514607585927
  0.12717812747627785
  0.01105679171823458
  0.07745559049870646
  0.29457111787580165

In [52]:
dxdxkψx_t = ForwardDiff.hessian(C.I.f.f, X[:,1])

2×2 Array{Float64,2}:
 -0.13341    -0.0150962
 -0.0150962   0.275081

In [ ]:
evaluate()

In [16]:
log_pdf(C, X)

8-element Array{Float64,1}:
 -1.890933371333304
 -1.0774421758804786
 -1.3812358207093065
 -2.756566903253647
 -2.2764943782683207
 -3.268114225886461
 -0.9741216255311081
 -1.442529469931936

In [18]:
Cx = evaluate(C, X)

8-element Array{Float64,1}:
 -1.3182090265735815
  0.5518744832820461
  1.0207836492619973
  1.969508900840876
  1.7095646000932772
  2.2193925767103297
  0.06731649217667446
  1.0856697228586412

In [22]:
getidx(C)

5×2 Array{Int64,2}:
 0  0
 0  1
 1  0
 1  1
 1  2

In [21]:
getcoeff(C)

5-element Array{Float64,1}:
  0.6285037650645056
 -0.4744029092496623
  1.1405280011620331
 -0.7217760771894809
  0.11855056306742319

In [23]:
dψ = grad_x_basis(C.I.f.f, X)

8×5×2 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0   0.107478    0.0190908  -0.043005
 0.0  0.0   0.0865389   0.0541193  -0.0107887
 0.0  0.0   0.138011    0.0855902   0.0231549
 0.0  0.0  -0.270698   -0.113793   -0.145219
 0.0  0.0  -0.259926   -0.128072   -0.127645
 0.0  0.0  -0.225594   -0.0869868  -0.122217
 0.0  0.0  -0.266312   -0.155186    0.0881003
 0.0  0.0   0.261878    0.157944    0.0678763

[:, :, 2] =
 0.0   0.200064   0.0   0.122532   -0.167233
 0.0   0.0623342  0.0   0.0386104   0.379666
 0.0  -0.0838875  0.0  -0.0502452   0.357862
 0.0  -0.268231   0.0  -0.105483    0.0306983
 0.0  -0.24554    0.0  -0.112246    0.113373
 0.0  -0.270878   0.0  -0.142266    0.00262786
 0.0   0.165408   0.0   0.0714071   0.211025
 0.0  -0.129595   0.0  -0.0583847   0.246624

In [24]:
d2ψ = hess_x_basis(C.I.f.f, X)

8×5×2×2 Array{Float64,4}:
[:, :, 1, 1] =
 0.0  0.0  -0.287372   -0.0510446    0.114986
 0.0  0.0  -0.297614   -0.18612      0.0371031
 0.0  0.0  -0.267679   -0.166006    -0.0449099
 0.0  0.0  -0.0102897  -0.00432547  -0.00552002
 0.0  0.0  -0.0807765  -0.0398007   -0.0396678
 0.0  0.0  -0.1657     -0.0638922   -0.089769
 0.0  0.0  -0.0515665  -0.030049     0.0170591
 0.0  0.0  -0.0730321  -0.0440471   -0.0189292

[:, :, 2, 1] =
 0.0   0.0   0.0   0.0215025   -0.0293467
 0.0   0.0   0.0   0.00539434   0.0530439
 0.0  -0.0   0.0  -0.0115774    0.0824581
 0.0  -0.0  -0.0   0.0726096   -0.0211313
 0.0  -0.0  -0.0   0.0638224   -0.0644633
 0.0  -0.0  -0.0   0.0611086   -0.00112877
 0.0   0.0  -0.0  -0.0440502   -0.130179
 0.0  -0.0   0.0  -0.0339381    0.143359

[:, :, 1, 2] =
 0.0   0.0   0.0   0.0215025   -0.0293467
 0.0   0.0   0.0   0.00539434   0.0530439
 0.0  -0.0   0.0  -0.0115774    0.0824581
 0.0  -0.0  -0.0   0.0726096   -0.0211313
 0.0  -0.0  -0.0   0.0638224   -0.0644633
 0.0  -

### Integration

In [20]:
Nx = 100
Ny = 50
m = 20
Ne = 400
X = randn(Nx, Ne).*randn(Nx, Ne) #.+ 0.5*randn(Nx).*cos.(randn(Nx, Ne) .* randn(Nx, Ne))

# L = LinearTransform(X)
# transform!(L, X);
# C = MapComponent(m, Nx)
# @time C, _ = optimize(C, X, 10)

In [24]:
M = HermiteMap(m, X);

In [25]:
@time M_noqr = optimize(M, X, 10; P = serial, start = Ny+1);

  9.550136 seconds (42.61 M allocations: 13.653 GiB, 7.59% gc time)


In [26]:
@time M_qr = optimize(M, X, 10; P = serial, withqr = true, start = Ny+1);

 18.997304 seconds (45.81 M allocations: 21.111 GiB, 4.17% gc time)


In [31]:
function timing()
    M = HermiteMap(m, X)
    @btime begin 
        optimize($M, $X, $10; P = serial, withqr = false, start = Ny+1)
    end
    
    @btime begin 
        optimize($M, $X, $10; P = serial, withqr = true, start = Ny+1)
    end
end

timing (generic function with 1 method)

In [32]:
timing();

  11.257 s (42606958 allocations: 13.65 GiB)
  21.346 s (45813192 allocations: 21.12 GiB)


In [11]:
timing();

  14.597 s (42433511 allocations: 13.37 GiB)


In [29]:
timing();

  973.450 ms (1054425 allocations: 1.43 GiB)


In [14]:
methods(update_component)

# 1 method for generic function "update_component":
[1] update_component(C::MapComponent, X, reduced_margin::Array{Int64,2}, S::Storage) in AdaptiveTransportMap at /media/mat/HDD/AdaptiveTransportMap/src/mapcomponent/greedyfit.jl:249

In [30]:
function timing()
    @btime begin 
        M = HermiteMap($m, $X)
        optimize($M, $X, $10; P = thread)
    end
end

timing (generic function with 1 method)

In [88]:
timing();

  297.730 ms (1000725 allocations: 1.35 GiB)


### Test optimization with QR

In [45]:
Nx = 3
Ne = 8
m = 20

idx = [0 0 0; 0 0 1; 0 1 0; 0 1 1; 0 1 2; 1 0 0]


Nψ = 6
coeff = [ 0.20649582065364197;
         -0.5150990160472986;
          2.630096893080717;
          1.13653076177397;
          0.6725837371023421;
         -1.3126095306624133]
C = MapComponent(m, Nx, idx, coeff; α = 1e-6);

Ne = 100


# The QR decomposition is not unique!

X = randn(Nx, Ne) .* randn(Nx, Ne) + cos.(randn(Nx, Ne)) .* exp.(-randn(Nx, Ne).^2)

L = LinearTransform(X)
transform!(L, X)
S = Storage(C.I.f, X)
F = QRscaling(S)
newidx = [1 1 1]

Snew = update_storage(S, X, newidx)
Fupdated = updateQRscaling(F, Snew)

Fnew = QRscaling(Snew)

@test norm(Fupdated.D - Fnew.D)<1e-8
@test norm(Fupdated.Dinv - Fnew.Dinv)<1e-8

Test Passed