In [1]:
using Pkg
Pkg.activate("/media/mat/HDD/AdaptiveTransportMap/")

 Activating environment at `/media/mat/HDD/AdaptiveTransportMap/Project.toml`


In [22]:
using Revise
using AdaptiveTransportMap
using LinearAlgebra
using Test
using ForwardDiff
using Optim
using OptimTestProblems

┌ Info: Precompiling OptimTestProblems [cec144fc-5a64-5bc6-99fb-dde8f63e154c]
└ @ Base loading.jl:1278


https://stackoverflow.com/questions/43158366/optim-jl-negative-inverse-hessian

In [65]:
prob = OptimTestProblems.UnconstrainedProblems.examples["Extended Powell"]

OptimTestProblems.MultivariateProblems.OptimizationProblem{OptimTestProblems.MultivariateProblems.UnconstrainedProblems.MatVecHolder{Array{Float64,1},Array{Float64,2}},typeof(OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell_fun_gradient!),Float64,String,Nothing}("Extended Powell (100)", OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell, OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell_gradient!, OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell_fun_gradient!, OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell_hessian!, nothing, [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.0, true, false, OptimTestProblems.MultivariateProblems.UnconstrainedProblems.MatVecHolder{Array{Float64,1},Array{Float64,2}}(Array{Float64}(undef,0,

In [66]:
x0 = prob.initial_x

100-element Array{Float64,1}:
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 3.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [67]:
obj = OnceDifferentiable(prob.f, prob.g!, x0)

OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1}}(OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell, OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell_gradient!, NLSolversBase.var"#fg!#8"{typeof(OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell),typeof(OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell_gradient!)}(OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell, OptimTestProblems.MultivariateProblems.UnconstrainedProblems.extpowell_gradient!), 0.0, [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN  …  NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN], [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN  …  NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN], [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN  …  NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN], [0], [0])

In [68]:
m = LBFGS()

LBFGS{Nothing,LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Optim.var"#17#19"}(10, LineSearches.InitialStatic{Float64}
  alpha: Float64 1.0
  scaled: Bool false
, LineSearches.HagerZhang{Float64,Base.RefValue{Bool}}
  delta: Float64 0.1
  sigma: Float64 0.9
  alphamax: Float64 Inf
  rho: Float64 5.0
  epsilon: Float64 1.0e-6
  gamma: Float64 0.66
  linesearchmax: Int64 50
  psi3: Float64 0.1
  display: Int64 0
  mayterminate: Base.RefValue{Bool}
, nothing, Optim.var"#17#19"(), Flat(), true)

In [69]:
options = Optim.Options()

                x_abstol = 0.0
                x_reltol = 0.0
                f_abstol = 0.0
                f_reltol = 0.0
                g_abstol = 1.0e-8
                g_reltol = 1.0e-8
          outer_x_abstol = 0.0
          outer_x_reltol = 0.0
          outer_f_abstol = 0.0
          outer_f_reltol = 0.0
          outer_g_abstol = 1.0e-8
          outer_g_reltol = 1.0e-8
           f_calls_limit = 0
           g_calls_limit = 0
           h_calls_limit = 0
       allow_f_increases = true
 allow_outer_f_increases = true
        successive_f_tol = 1
              iterations = 1000
        outer_iterations = 1000
             store_trace = false
           trace_simplex = false
              show_trace = false
          extended_trace = false
              show_every = 1
                callback = nothing
              time_limit = NaN


In [70]:
lbfgsstate = Optim.initial_state(m, options, obj, x0)

LoadError: MethodError: no method matching extpowell_gradient!(::Array{Float64,1}, ::Array{Float64,1})
Closest candidates are:
  extpowell_gradient!(::AbstractArray, ::AbstractArray, ::OptimTestProblems.MultivariateProblems.UnconstrainedProblems.MatVecHolder) at /home/mat/.julia/packages/OptimTestProblems/Y2KeO/src/optim_tests/multivariate/more_testing.jl:103

In [56]:
res = Optim.optimize(obj, x0, m, options, lbfgsstate)

 * Status: success

 * Candidate solution
    Final objective value:     8.809762e-22

 * Found with
    Algorithm:     L-BFGS

 * Convergence measures
    |x - x'|               = 3.93e-07 ≰ 0.0e+00
    |x - x'|/|x'|          = 1.31e-07 ≰ 0.0e+00
    |f(x) - f(x')|         = 3.24e-12 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 3.67e+09 ≰ 0.0e+00
    |g(x)|                 = 2.99e-10 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    7
    f(x) calls:    83
    ∇f(x) calls:   83


In [58]:
lbfgsstate.rho

10-element Array{Float64,1}:
   0.057996387008704235
   0.17107101096570362
   0.8588451556494114
   4.7931509202222315
 602.6338656770724
   2.4257198702975223e6
   1.545335431712599e11
 NaN
 NaN
 NaN

In [49]:
H=similar(bfgsstate.invH)

2×2 Array{Float64,2}:
 6.95134e-310  6.95134e-310
 6.95136e-310  0.0

In [33]:
prob.h!(H, Optim.minimizer(res))

34.00000000000734

In [34]:
H

2×2 Array{Float64,2}:
 74.0  20.0
 20.0  34.0

In [35]:
inv(H)

2×2 Array{Float64,2}:
  0.0160681  -0.0094518
 -0.0094518   0.0349716

In [18]:
f(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2

x0 = [0.0, 0.0]

function g!(G, x)
G[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
G[2] = 200.0 * (x[2] - x[1]^2)
end

function h!(H, x)
    H[1, 1] = 2.0 - 400.0 * x[2] + 1200.0 * x[1]^2
    H[1, 2] = -400.0 * x[1]
    H[2, 1] = -400.0 * x[1]
    H[2, 2] = 200.0
end

Optim.optimize(f, g!, h!, x0)

 * Status: success

 * Candidate solution
    Final objective value:     3.081488e-31

 * Found with
    Algorithm:     Newton's Method

 * Convergence measures
    |x - x'|               = 3.06e-09 ≰ 0.0e+00
    |x - x'|/|x'|          = 3.06e-09 ≰ 0.0e+00
    |f(x) - f(x')|         = 9.34e-18 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 3.03e+13 ≰ 0.0e+00
    |g(x)|                 = 1.11e-15 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    14
    f(x) calls:    44
    ∇f(x) calls:   44
    ∇²f(x) calls:  14


In [21]:
?mod1

search: mod1 fldmod1 @macroexpand1 modf mod module mod2pi Model Module chmod



```
mod1(x, y)
```

Modulus after flooring division, returning a value `r` such that `mod(r, y) == mod(x, y)` in the range $(0, y]$ for positive `y` and in the range $[y,0)$ for negative `y`.

See also: [`fld1`](@ref), [`fldmod1`](@ref).

# Examples

```jldoctest
julia> mod1(4, 2)
2

julia> mod1(4, 3)
1
```


In [20]:
Optim.optimize(f, g!, h!, x0, LBFGS())

 * Status: success

 * Candidate solution
    Final objective value:     5.191703e-27

 * Found with
    Algorithm:     L-BFGS

 * Convergence measures
    |x - x'|               = 4.58e-11 ≰ 0.0e+00
    |x - x'|/|x'|          = 4.58e-11 ≰ 0.0e+00
    |f(x) - f(x')|         = 4.41e-19 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 8.50e+07 ≰ 0.0e+00
    |g(x)|                 = 1.44e-13 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    24
    f(x) calls:    67
    ∇f(x) calls:   67


In [15]:
Optim.optimize(f, g!, x0, BFGS())

 * Status: success

 * Candidate solution
    Final objective value:     7.645563e-21

 * Found with
    Algorithm:     BFGS

 * Convergence measures
    |x - x'|               = 3.48e-07 ≰ 0.0e+00
    |x - x'|/|x'|          = 3.48e-07 ≰ 0.0e+00
    |f(x) - f(x')|         = 6.91e-14 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 9.03e+06 ≰ 0.0e+00
    |g(x)|                 = 2.32e-09 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    16
    f(x) calls:    53
    ∇f(x) calls:   53


In [8]:
result = Optim.optimize(rosenbrock, zeros(2), LBFGS())

 * Status: success

 * Candidate solution
    Final objective value:     5.378388e-17

 * Found with
    Algorithm:     L-BFGS

 * Convergence measures
    |x - x'|               = 4.54e-11 ≰ 0.0e+00
    |x - x'|/|x'|          = 4.54e-11 ≰ 0.0e+00
    |f(x) - f(x')|         = 2.85e-19 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 5.30e-03 ≰ 0.0e+00
    |g(x)|                 = 9.88e-14 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    24
    f(x) calls:    67
    ∇f(x) calls:   67


In [8]:
function timing()
    result = optimize(rosenbrock, zeros(2), LBFGS())
end

timing (generic function with 1 method)

In [9]:
function f(x)
    return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
end

function g!(G, x)
    G[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
    G[2] = 200.0 * (x[2] - x[1]^2)
end

function h!(H, x)
    H[1, 1] = 2.0 - 400.0 * x[2] + 1200.0 * x[1]^2
    H[1, 2] = -400.0 * x[1]
    H[2, 1] = -400.0 * x[1]
    H[2, 2] = 200.0
end

initial_x = zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [17]:
@time Optim.minimizer(optimize(f, g!, h!, initial_x, BFGS()))

  0.000070 seconds (476 allocations: 20.172 KiB)


2-element Array{Float64,1}:
 0.9999999999373613
 0.9999999998686219

In [18]:
function fg!(F,G,x)
  # do common computations here
  # ...
  if G != nothing
    G[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
    G[2] = 200.0 * (x[2] - x[1]^2)
    # code to compute gradient here
    # writing the result to the vector G
  end
  if F != nothing
    value = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
    # value = ... code to compute objective function
    return value
  end
end

fg! (generic function with 1 method)

In [34]:
x0 = zeros(2);

In [2]:
?ldiv!

┌ Error: Failed to revise /media/mat/HDD/AdaptiveTransportMap/src/hermitemap.jl
│   exception = (ErrorException("/media/mat/HDD/AdaptiveTransportMap/src/hermitemap.jl is not stored in the source-text cache"), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007fccf5462f17, Ptr{Nothing} @0x00007fcccd8a8c0c, Ptr{Nothing} @0x00007fcccd8a8e35, Ptr{Nothing} @0x00007fcccd8a7ec2, Ptr{Nothing} @0x00007fcccd823afd])
└ @ Revise /home/mat/.julia/packages/Revise/BqeJF/src/Revise.jl:760
┌ Error: Failed to revise /media/mat/HDD/AdaptiveTransportMap/src/storage.jl
│   exception = (ErrorException("/media/mat/HDD/AdaptiveTransportMap/src/storage.jl is not stored in the source-text cache"), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007fccf5462f17, Ptr{Nothing} @0x00007fcccd8a8c0c, Ptr{Nothing} @0x00007fcccd8a8e35, Ptr{Nothing} @0x00007fcccd8a7ec2, Ptr{Nothing} @0x00007fcccd823afd])
└ @ Revise /home/mat/.julia/packages/Revise/BqeJF/src/Revise.jl:760
┌ Error: Failed to revise /med

search: ldiv! splitdrive



```
ldiv!(Y, A, B) -> Y
```

Compute `A \ B` in-place and store the result in `Y`, returning the result.

The argument `A` should *not* be a matrix.  Rather, instead of matrices it should be a factorization object (e.g. produced by [`factorize`](@ref) or [`cholesky`](@ref)). The reason for this is that factorization itself is both expensive and typically allocates memory (although it can also be done in-place via, e.g., [`lu!`](@ref)), and performance-critical situations requiring `ldiv!` usually also require fine-grained control over the factorization of `A`.

# Examples

```jldoctest
julia> A = [1 2.2 4; 3.1 0.2 3; 4 1 2];

julia> X = [1; 2.5; 3];

julia> Y = zero(X);

julia> ldiv!(Y, qr(A), X);

julia> Y
3-element Array{Float64,1}:
  0.7128099173553719
 -0.051652892561983674
  0.10020661157024757

julia> A\X
3-element Array{Float64,1}:
  0.7128099173553719
 -0.05165289256198333
  0.10020661157024785
```

---

```
ldiv!(A, B)
```

Compute `A \ B` in-place and overwriting `B` to store the result.

The argument `A` should *not* be a matrix.  Rather, instead of matrices it should be a factorization object (e.g. produced by [`factorize`](@ref) or [`cholesky`](@ref)). The reason for this is that factorization itself is both expensive and typically allocates memory (although it can also be done in-place via, e.g., [`lu!`](@ref)), and performance-critical situations requiring `ldiv!` usually also require fine-grained control over the factorization of `A`.

# Examples

```jldoctest
julia> A = [1 2.2 4; 3.1 0.2 3; 4 1 2];

julia> X = [1; 2.5; 3];

julia> Y = copy(X);

julia> ldiv!(qr(A), X);

julia> X
3-element Array{Float64,1}:
  0.7128099173553719
 -0.051652892561983674
  0.10020661157024757

julia> A\Y
3-element Array{Float64,1}:
  0.7128099173553719
 -0.05165289256198333
  0.10020661157024785
```

---

```
ldiv!(a::Number, B::AbstractArray)
```

Divide each entry in an array `B` by a scalar `a` overwriting `B` in-place.  Use [`rdiv!`](@ref) to divide scalar from right.

# Examples

```jldoctest
julia> B = [1.0 2.0; 3.0 4.0]
2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

julia> ldiv!(2.0, B)
2×2 Array{Float64,2}:
 0.5  1.0
 1.5  2.0
```

---

Solve Hy = rhs for a non-square Hessenberg matrix. Note that `H` is also modified as is it converted to an upper triangular matrix via Given's rotations


In [51]:
res = Optim.optimize(Optim.only_fg!(fg!), x0, Optim.LBFGS())
@time Optim.minimizer(res)

  0.000003 seconds


2-element Array{Float64,1}:
 0.999999999999928
 0.9999999999998559

In [47]:
fieldnames(typeof(res))

(:method, :initial_x, :minimizer, :minimum, :iterations, :iteration_converged, :x_converged, :x_abstol, :x_reltol, :x_abschange, :x_relchange, :f_converged, :f_abstol, :f_reltol, :f_abschange, :f_relchange, :g_converged, :g_abstol, :g_residual, :f_increased, :trace, :f_calls, :g_calls, :h_calls, :ls_success, :time_limit, :time_run)

In [33]:
function fgh!(F,G,H,x)
    if F != nothing
        return f(x)
    end
    if G != nothing
        g!(G, x)
        return G
    end
    
    if H != nothing
        h!(H, x)
        return H
    end
end

Optim.optimize(Optim.only_fgh!(fgh!), [0., 0.], Optim.Newton())

 * Status: failure (objective increased between iterations)

 * Candidate solution
    Final objective value:     1.000000e+00

 * Found with
    Algorithm:     Newton's Method

 * Convergence measures
    |x - x'|               = 1.00e-06 ≰ 0.0e+00
    |x - x'|/|x'|          = 1.00e+00 ≰ 0.0e+00
    |f(x) - f(x')|         = 1.00e-06 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 1.00e-06 ≰ 0.0e+00
    |g(x)|                 = 8.80e-02 ≰ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    1
    f(x) calls:    71
    ∇f(x) calls:   71
    ∇²f(x) calls:  2


In [28]:
function timing()
    @btime optimize(rosenbrock, zeros(2), LBFGS())
    @btime Optim.optimize(Optim.only_fg!(fg!), [0., 0.], Optim.LBFGS())
    @btime Optim.optimize(Optim.only_fgh!(fgh!), [0., 0.], Optim.Newton())
end

timing (generic function with 1 method)

In [29]:
timing()

  42.254 μs (578 allocations: 27.69 KiB)
  37.231 μs (572 allocations: 27.59 KiB)


ArgumentError: ArgumentError: Value and slope at step length = 0 must be finite.