In [3]:
using Revise
using LinearAlgebra
using AdaptiveTransportMap
using Statistics
using Distributions
using Test
using ForwardDiff
using SpecialFunctions
using OrthoMatchingPursuit

┌ Info: Precompiling AdaptiveTransportMap [bdf749b0-1400-4207-80d3-e689c0e3f03d]
└ @ Base loading.jl:1278
┌ Warning: Type annotations on keyword arguments not currently supported in recipes. Type information has been discarded
└ @ RecipesBase ~/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:116
┌ Warning: Type annotations on keyword arguments not currently supported in recipes. Type information has been discarded
└ @ RecipesBase ~/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:116


In [134]:
Nx = 5
Ne = 100

X = randn(Nx, Ne) .* randn(Nx, Ne)

λ = 0.0
δ = 0.0
γ = 2.0

2.0

In [135]:
@time Cgreedy = greedyfit(Nx, 2, X, 3, λ, δ, γ)

candidates = [1, 2, 3, 4]
new_dim = 2
offdims = [2]
candidates = [1, 3, 4]
candidates = [1, 3, 4]
new_dim = 4
offdims = [2, 4]
candidates = [1, 3]
candidates = [1, 3]
new_dim = 1
offdims = [2, 4, 1]
candidates = [3]
  0.264751 seconds (464.61 k allocations: 25.125 MiB)


5-th component of a Sparse KR rearrangement of order p = [2, 2, -1, 2, 2]


In [127]:
Cgreedy.p

5-element Array{Int64,1}:
  2
  2
 -1
  2
  2

In [129]:
p = 2
order = p*ones(Int64, Nx)
order[1] = p
order[end] = p

order = [p; p; -1; p; p]

λ = 0.0
δ = 0.0
γ = 2.0

C = SparseRadialMapComponent(Nx, order)
center_std!(C, sort(X; dims = 2); γ = γ)

xdiag = optimize(C, X, λ, δ)
modify_a!(C, xdiag)

In [130]:
C.a

5-element Array{Array{Float64,1},1}:
 [0.06692085832073022, -0.7801398484959575, 0.6002539523221105]
 [-0.07939138121491598, 0.6004935199273379, -0.2402751136767193]
 []
 [0.13919029269758154, 0.18028587071195884, -0.28434514120169146]
 [-1.2434054385111921, 0.43945797002398135, 0.5294516517672112, 2.071789145456753, 0.4994167451044891]

In [131]:
Cgreedy.a

5-element Array{Array{Float64,1},1}:
 [0.06692085832073022, -0.7801398484959575, 0.6002539523221105]
 [-0.07939138121491598, 0.6004935199273379, -0.2402751136767193]
 []
 [0.13919029269758154, 0.18028587071195884, -0.28434514120169146]
 [-1.2434054385111921, 0.43945797002398135, 0.5294516517672112, 2.071789145456753, 0.4994167451044891]

In [ ]:
@time S = greedyfit(Nx, 2, X, 3, λ, δ, γ)

In [44]:
p = 2
order = -1*ones(Int64, Nx)
order[end] = p

λ = 0.0
δ = 0.0
γ = 2.0

C = SparseRadialMapComponent(Nx, order)

center_std!(C, X; γ = γ)

In [43]:
xdiag = optimize(C, X, λ, δ)
@show xdiag
modify_a!(C, xdiag)

nd = 4
xdiag = [-1.144856912325688, 0.5117073506980931, 1.267987430300984, 0.9882418961056991, 0.628141290464556]


In [74]:
C.ξ[1] = zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [77]:
candidate = [1;2;4;5;6]

5-element Array{Int64,1}:
 1
 2
 4
 5
 6

In [79]:
filter!(x-> x!= 6, candidate)

4-element Array{Int64,1}:
 1
 2
 4
 5

In [58]:
F = qrfactUnblocked(zeros(0,0))

QR{Float64,Array{Float64,2}}
Q factor:
0×0 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}
R factor:
0×0 Array{Float64,2}

In [59]:
sort(X; dims = 2)

3×100 Array{Float64,2}:
 -3.19543  -1.91949  -1.79685  …  1.5624   2.02908  2.07783  2.57984
 -2.56403  -2.16018  -1.79746     1.95061  1.99873  2.22     2.45416
 -5.25837  -2.23524  -2.21159     1.82776  1.88725  3.68546  4.48272

In [60]:
fieldnames(typeof(C))

(:Nx, :p, :activedim, :ξ, :σ, :a)

In [61]:
# Create a radial map with order p for all the entries
Cfull = SparseRadialMapComponent(Nx, p)

# Compute centers and widths
center_std!(Cfull, X; γ = 2.0)

In [62]:
### Evaluate the different basis

# Create weights
ψ_off, ψ_diag, ψ_∂k = compute_weights(Cfull, X)

([-0.05265181235741307 0.4779324710910178 … 0.08398298544273618 -0.4092296050232699; 0.6335110135727616 0.426100046813958 … 0.6122688072606001 0.5544757104159953; … ; 0.5008613639194552 0.5177783763757736 … 0.07474742681337398 0.0786362808665519; 0.37659543336751466 0.5025194820224516 … 0.02455226721309088 0.026165363552809188], [-0.014673891188928027 -0.12616874894278474 … -0.0031674895288425556 -0.47026981960161884; 0.7903899800904021 0.4137352925063087 … 0.9096863222326221 0.10075390680759361; 0.5611286279792064 0.3043548121365823 … 0.6909381256481013 0.1151723813223477; 0.2358548010139806 0.09826103084808677 … 0.34567108006812614 0.032301303888060656], [0.07479940760187515 0.402794218988961 … 0.01972064278811092 0.8383859151017649; 0.563951079932745 0.7631598027503205 … 0.318935996711231 0.3456793730256319; 0.5012697751851327 0.444943515223901 … 0.4479670755249779 0.24705496505617405; 0.3527810546164679 0.182315034146949 … 0.4585573932228423 0.07316008586299144])

In [63]:
C.p

3-element Array{Int64,1}:
 -1
 -1
  2

In [64]:
C.a[2]

Float64[]

In [65]:
xoff = zeros(6)

6-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [66]:
xdiag

5-element Array{Float64,1}:
 -1.708651306570871
  0.023853011531796413
  0.9476620071459296
  2.3229272697140018
  0.26632668197579334

In [85]:
@time σψ_off = norm.(eachslice(ψ_off; dims = 1))

  0.000017 seconds (7 allocations: 560 bytes)


6-element Array{Float64,1}:
 9.059531047355486
 4.7997094847545965
 4.694335089300771
 8.736553330288878
 4.077485689847407
 4.059224468063335

In [88]:
?mul!

search: mul! rmul! lmul! accumulate! elementproductmatmul! muladd MultiBasis



```
mul!(Y, A, B) -> Y
```

Calculates the matrix-matrix or matrix-vector product $AB$ and stores the result in `Y`, overwriting the existing value of `Y`. Note that `Y` must not be aliased with either `A` or `B`.

# Examples

```jldoctest
julia> A=[1.0 2.0; 3.0 4.0]; B=[1.0 1.0; 1.0 1.0]; Y = similar(B); mul!(Y, A, B);

julia> Y
2×2 Array{Float64,2}:
 3.0  3.0
 7.0  7.0
```

# Implementation

For custom matrix and vector types, it is recommended to implement 5-argument `mul!` rather than implementing 3-argument `mul!` directly if possible.

---

```
mul!(C, A, B, α, β) -> C
```

Combined inplace matrix-matrix or matrix-vector multiply-add $A B α + C β$. The result is stored in `C` by overwriting it.  Note that `C` must not be aliased with either `A` or `B`.

!!! compat "Julia 1.3"
    Five-argument `mul!` requires at least Julia 1.3.


# Examples

```jldoctest
julia> A=[1.0 2.0; 3.0 4.0]; B=[1.0 1.0; 1.0 1.0]; C=[1.0 2.0; 3.0 4.0];

julia> mul!(C, A, B, 100.0, 10.0) === C
true

julia> C
2×2 Array{Float64,2}:
 310.0  320.0
 730.0  740.0
```

---

Do mul! with the off-diagonal elements of a matrix.


In [89]:
A = randn(10,3)

10×3 Array{Float64,2}:
 -0.853656  -1.44137    0.156286
  0.940509   0.555801  -0.311858
 -0.718136  -1.48009   -0.460115
 -0.325371  -1.74338   -0.691796
  0.738981  -0.246861  -1.15411
  0.803276  -1.00937   -0.638441
 -0.576057  -0.709121  -1.54447
 -1.07807    1.97736    0.493205
 -0.142008   0.299562   1.24071
 -1.78193   -1.29644   -0.743333

In [90]:
σA = norm.(eachcol(A))

3-element Array{Float64,1}:
 2.8488117348971618
 3.8574078376024805
 2.6966820879796654

In [92]:
B = A ./ σA'

10×3 Array{Float64,2}:
 -0.299653  -0.373664    0.0579551
  0.330141   0.144087   -0.115645
 -0.252083  -0.383702   -0.170623
 -0.114213  -0.451956   -0.256536
  0.2594    -0.0639966  -0.427976
  0.281969  -0.261671   -0.23675
 -0.202209  -0.183834   -0.572729
 -0.378428   0.512614    0.182893
 -0.049848   0.077659    0.460087
 -0.625499  -0.336091   -0.275647

In [100]:
norm(B)-sqrt(3)

┌ Error: Failed to revise /media/mat/HDD/AdaptiveTransportMap/src/radialmap/greedyfit.jl
│   exception = (LoadError("/media/mat/HDD/AdaptiveTransportMap/src/radialmap/greedyfit.jl", 61, "missing last argument in \"2:\" range expression "), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007ff4d2255fd3])
└ @ Revise /home/mat/.julia/packages/Revise/AIcio/src/packagedef.jl:709


0.0

In [67]:
L(x) = (1/(2*Ne))*norm((ψ_off'*x) + ψ_diag'*xdiag[2:end] .+ xdiag[1])^2 + λ*x'*x

L (generic function with 1 method)

In [68]:
ForwardDiff.gradient(x->L(x), xoff)

6-element Array{Float64,1}:
  0.1165972042950302
 -0.006018497994904082
 -0.005511133462771722
  0.0016074796330899544
  0.016452355156386912
  0.01495891361857412

In [97]:
?BLAS.gemm!

```
gemm!(tA, tB, alpha, A, B, beta, C)
```

Update `C` as `alpha*A*B + beta*C` or the other three variants according to [`tA`](@ref stdlib-blas-trans) and `tB`. Return the updated `C`.


In [71]:
b = vcat(ones(1,Ne), ψ_diag)'*xdiag;
J = 1/Ne*(ψ_off)*ψ_off'*xoff #+ (1/(2*Ne))*ψ_off*b + ((1/(2*Ne))*b'*ψ_off')' + λ*xoff           
J = 1/Ne*(ψ_off)*(ψ_off'*xoff) + (1/(Ne))*ψ_off*b  + λ*xoff           

6-element Array{Float64,1}:
  0.11659720429503018
 -0.006018497994904076
 -0.005511133462771721
  0.0016074796330899405
  0.016452355156386905
  0.014958913618574099

In [99]:
?mul!

search: mul! rmul! lmul! accumulate! elementproductmatmul! muladd MultiBasis



┌ Error: Failed to revise /media/mat/HDD/AdaptiveTransportMap/src/radialmap/greedyfit.jl
│   exception = (LoadError("/media/mat/HDD/AdaptiveTransportMap/src/radialmap/greedyfit.jl", 61, "missing last argument in \"2:\" range expression "), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007ff4d2255fd3])
└ @ Revise /home/mat/.julia/packages/Revise/AIcio/src/packagedef.jl:709


```
mul!(Y, A, B) -> Y
```

Calculates the matrix-matrix or matrix-vector product $AB$ and stores the result in `Y`, overwriting the existing value of `Y`. Note that `Y` must not be aliased with either `A` or `B`.

# Examples

```jldoctest
julia> A=[1.0 2.0; 3.0 4.0]; B=[1.0 1.0; 1.0 1.0]; Y = similar(B); mul!(Y, A, B);

julia> Y
2×2 Array{Float64,2}:
 3.0  3.0
 7.0  7.0
```

# Implementation

For custom matrix and vector types, it is recommended to implement 5-argument `mul!` rather than implementing 3-argument `mul!` directly if possible.

---

```
mul!(C, A, B, α, β) -> C
```

Combined inplace matrix-matrix or matrix-vector multiply-add $A B α + C β$. The result is stored in `C` by overwriting it.  Note that `C` must not be aliased with either `A` or `B`.

!!! compat "Julia 1.3"
    Five-argument `mul!` requires at least Julia 1.3.


# Examples

```jldoctest
julia> A=[1.0 2.0; 3.0 4.0]; B=[1.0 1.0; 1.0 1.0]; C=[1.0 2.0; 3.0 4.0];

julia> mul!(C, A, B, 100.0, 10.0) === C
true

julia> C
2×2 Array{Float64,2}:
 310.0  320.0
 730.0  740.0
```

---

Do mul! with the off-diagonal elements of a matrix.


In [41]:
norm(J[4:6])

LoadError: UndefVarError: J not defined

In [ ]:
@testset "Verify updateqrfactUnblocked! for a vector" begin

    ψ = randn(100, 20)
    ϕ = randn(100)

    F = qrfactUnblocked(ψ)
    Fold = deepcopy(F)
    G = qrfactUnblocked(hcat(ψ, ϕ))
    F = updateqrfactUnblocked!(F, ϕ)
    @test norm(F.τ-G.τ)<1e-14
    @test norm(F.factors - G.factors)<1e-14
end

@testset "Verify updateqrfactUnblocked! for a matrix" begin

    ψ = randn(100, 20)
    ϕ = randn(100, 5)

    F = qrfactUnblocked(ψ)
    Fold = deepcopy(F)
    G = qrfactUnblocked(hcat(ψ, ϕ))
    F = updateqrfactUnblocked!(F, ϕ)
    @test norm(F.τ-G.τ)<1e-14
    @test norm(F.factors - G.factors)<1e-14
end