In [1]:
using Revise
using LinearAlgebra
using AdaptiveTransportMap
using Statistics
using Distributions
using Test
using ForwardDiff
using SpecialFunctions

┌ Info: Precompiling AdaptiveTransportMap [bdf749b0-1400-4207-80d3-e689c0e3f03d]
└ @ Base loading.jl:1278
┌ Warning: Type annotations on keyword arguments not currently supported in recipes. Type information has been discarded
└ @ RecipesBase ~/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:116
┌ Warning: Type annotations on keyword arguments not currently supported in recipes. Type information has been discarded
└ @ RecipesBase ~/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:116


In [2]:
Nx = 3
Ne = 100

X = randn(Nx, Ne) .* randn(Nx, Ne)

3×100 Array{Float64,2}:
 -0.749731  -0.187909    0.328724  …  -0.140462  -0.0061916  -1.85843
 -0.610297   0.0814882   0.536478      0.268093   1.36918    -1.49243
 -0.663116  -0.258397   -0.627452      0.196283  -0.29078     0.289339

In [12]:
p = 2
order = [[-1], [p; p], [p; -1; p]]
# parameters of the radial map
γ = 2.0
λ = 0.0
δ = 1e-8
κ = 10.0
β = 1.0

1.0

In [18]:
S[3].activedim

2-element Array{Int64,1}:
 1
 3

In [20]:
intersect(1:Nx-1, [1; 3])

1-element Array{Int64,1}:
 1

In [17]:
S = SparseRadialMap(Nx, order; γ = γ, λ = λ, δ = δ, κ = κ)

Sparse Radial Map of dimension Nx = 3 and order p = [[-1], [2, 2], [2, -1, 2]]
        with parameters (γ, λ, δ, κ) = (2.0, 0.0, 1.0e-8, 10.0)


In [6]:
# Compute centers and widths
center_std(S, X)

In [6]:
ψ_off, ψ_mono, dψ_mono = weights(S[3], X)

([0.03045548552433473 1.7247424147778092 … 0.5573117853232217 1.850187301271166; 0.42804472227875456 0.05396444709934926 … 0.3246171447632195 0.0403924938733677; … ; 0.40060440666270336 0.38003965971899495 … 0.39407204830550757 0.37670058535954054; 0.3772897232879792 0.3994727227651369 … 0.31104960256641406 0.4008198230612497], [-0.32102288036854676 -0.07494407577738146 … -0.0658257334894152 -0.26905685959675363; 0.2942848900526415 0.7441079509493826 … 0.77164250792433 0.3562611805932012; 0.17049730570544658 0.6313280621631854 … 0.6664945823949311 0.22162691032229348; 0.040123535863675036 0.2353510274902077 … 0.26091465344146075 0.054172484917337324], [0.46512123261110494 0.15859054156515812 … 0.1428671236356865 0.41331337416685043; 0.5022110627161585 0.4687658313352641 … 0.4406916859496858 0.5431724566444791; 0.3973960154673769 0.5911324156467163 … 0.5700466646349909 0.46607903341494317; 0.10453360311860088 0.4076153023750737 … 0.43709471688020757 0.1337501778465074])

In [7]:
ψ_off

6×100 Array{Float64,2}:
  0.0304555   1.72474    0.073244   …   0.0684391   0.557312   1.85019
  0.428045    0.0539644  0.423747       0.424274    0.324617   0.0403925
  0.415888    0.132348   0.421454       0.420871    0.420633   0.106092
 -0.300296   -0.0833889  0.0782703     -0.0903031  -0.649108  -0.0593117
  0.400604    0.38004    0.354114       0.380962    0.394072   0.376701
  0.37729     0.399473   0.403971   …   0.399043    0.31105    0.40082

In [8]:
ψ_mono

4×100 Array{Float64,2}:
 -0.321023   -0.0749441  -0.0456151  …  -0.193564   -0.0658257  -0.269057
  0.294285    0.744108    0.837038       0.471612    0.771643    0.356261
  0.170497    0.631328    0.753758       0.327453    0.666495    0.221627
  0.0401235   0.235351    0.338926       0.0875718   0.260915    0.0541725

In [11]:
optimize(S, X)

In [12]:
S(X)

2×100 Array{Float64,2}:
 -0.0902116  -0.12386    1.14741  …  -0.00547935   0.236258   1.08684
  1.55339     0.0265068  1.62471     -0.117889    -0.213312  -0.116376

In [14]:
S[2].a

2-element Array{Array{Float64,1},1}:
 [-0.058027779437800964, -0.2624711875861948, 0.10687681878653094]
 [-1.0381593282757833, 0.5530618586357308, 1.8397629885942306, 3.355907582232706e-8, 0.8073814716517264]

In [15]:
z = randn(3)

3-element Array{Float64,1}:
 -1.0624153447017135
  0.14936612885034695
 -0.5724227536520541

In [17]:
S[2].a[1] .= z

3-element Array{Float64,1}:
 -1.0624153447017135
  0.14936612885034695
 -0.5724227536520541

In [19]:
S[2].a[2] = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [38]:
active_dim = Int64[]
push!(active_dim, 4)

1-element Array{Int64,1}:
 4

In [39]:
push!(active_dim, 5)

2-element Array{Int64,1}:
 4
 5

In [9]:
p = [1; 1;2; -1; 2]

┌ Error: Failed to revise /media/mat/HDD/AdaptiveTransportMap/src/radialmap/sparseradialmapcomponent.jl
│   exception = Revise.ReviseEvalException("/media/mat/HDD/AdaptiveTransportMap/src/radialmap/sparseradialmapcomponent.jl:10", ErrorException("invalid redefinition of constant SparseRadialMapComponent"), Any[(top-level scope at sparseradialmapcomponent.jl:10, 1)])
└ @ Revise /home/mat/.julia/packages/Revise/AIcio/src/packagedef.jl:707
┌ Warning: The running code does not match the saved version for the following files:
│ 
│   /media/mat/HDD/AdaptiveTransportMap/src/radialmap/sparseradialmapcomponent.jl
│ 
│ If the error was due to evaluation order, it can sometimes be resolved by calling `Revise.retry()`.
│ Use Revise.errors() to report errors again. Only the first error in each file is shown.
│ Your prompt color may be yellow until the errors are resolved.
└ @ Revise /home/mat/.julia/packages/Revise/AIcio/src/packagedef.jl:805


5-element Array{Int64,1}:
  1
  1
  2
 -1
  2

In [ ]:
julia> a = 1:10
1:10

julia> filter(isodd, a)
5-element Array{Int64,1}:
 1
 3
 5
 7

In [13]:
?filter

Return a copy of collection a, removing elements for which f is false.

search:

Couldn't find filter

Return a copy of collection a, removing elements for which f is false.
Perhaps you meant FisherNoncentralHypergeometric


No documentation found.

Binding `filter

Return a copy of collection a, removing elements for which f is false.` does not exist.


In [28]:
p[4] = 2

2

In [31]:
p = -1*ones(Int64,5)

5-element Array{Int64,1}:
 -1
 -1
 -1
 -1
 -1

In [24]:
using BenchmarkTools

In [32]:
p[p .!= -1]

Int64[]

In [26]:
@btime filter(x-> x != -1, p)

  40.442 ns (1 allocation: 128 bytes)


4-element Array{Int64,1}:
 1
 1
 2
 2

In [ ]:
@testset "Verify updateqrfactUnblocked! for a vector" begin

    ψ = randn(100, 20)
    ϕ = randn(100)

    F = qrfactUnblocked(ψ)
    Fold = deepcopy(F)
    G = qrfactUnblocked(hcat(ψ, ϕ))
    F = updateqrfactUnblocked!(F, ϕ)
    @test norm(F.τ-G.τ)<1e-14
    @test norm(F.factors - G.factors)<1e-14
end

@testset "Verify updateqrfactUnblocked! for a matrix" begin

    ψ = randn(100, 20)
    ϕ = randn(100, 5)

    F = qrfactUnblocked(ψ)
    Fold = deepcopy(F)
    G = qrfactUnblocked(hcat(ψ, ϕ))
    F = updateqrfactUnblocked!(F, ϕ)
    @test norm(F.τ-G.τ)<1e-14
    @test norm(F.factors - G.factors)<1e-14
end