In [ ]:
using Revise
using LinearAlgebra
using AdaptiveTransportMap
using Statistics
using Distributions
using Test
using ForwardDiff
using SpecialFunctions
using OrthoMatchingPursuit

┌ Info: Precompiling AdaptiveTransportMap [bdf749b0-1400-4207-80d3-e689c0e3f03d]
└ @ Base loading.jl:1278
┌ Warning: Type annotations on keyword arguments not currently supported in recipes. Type information has been discarded
└ @ RecipesBase ~/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:116
┌ Warning: Type annotations on keyword arguments not currently supported in recipes. Type information has been discarded
└ @ RecipesBase ~/.julia/packages/RecipesBase/92zOw/src/RecipesBase.jl:116


In [ ]:
A = randn(10, 5)

In [ ]:
mean(A; dims = 1)[1,:]

In [ ]:
@testset "Test optimization for Nx=1 and p=0" begin
   Nx = 1
   Ne = 10
   p = 0
   γ = 2.0


   X = reshape([-1.5438
      -1.5518
       0.8671
      -0.1454
      -0.3862
       1.3162
      -0.7965
       0.1354
       0.4178
       0.8199],1,Ne)


   S = RadialMap(Nx, p; γ = γ);
   W = create_weights(S, X)
   center_std!(S, X);
   compute_weights(S, X, W)

   # With λ = δ = 0.0

   λ = 0.0
   δ = 0.0
   xopt = optimize(S.C[1], W, λ, δ);

   @test norm(xopt - [0.092087627168250; 1.061773632748180])<1e-10

   # With λ = 0.1 and δ = 1e-8

   λ = 0.1
   δ = 1e-8
   xopt = optimize(S.C[1], W, λ, δ);

   @test norm(xopt - [ 0.092087627168250; 1.061773632748180])<1e-10

end

@testset "Test optimization for Nx=2 and p=0" begin

    Nx = 2
    Ne = 10
    p = 0
    γ = 2.0
    λ = 0.0

    X = Matrix([-0.8544   -0.7938;0.3573    0.5410; 2.7485   -0.5591; -1.5130    1.9766; 0.4340    0.5447; -0.2298   -0.1379;-0.8271   0.6199;-0.8320   -0.0056;0.4979    1.1072;2.3156   -0.1856]')

    @time S = RadialMap(Nx, p; γ = γ)

    center_std!(S, X)
    W = create_weights(S, X)
   compute_weights(S, X, W)

    # With λ = δ = 0.0

    λ = 0.0
    δ = 0.0

    xopt = optimize(S.C[2], W, λ, δ)

    @test norm(xopt -[0.357284296467942; -0.513627363149479; 1.411806803694895 ])<1e-10

    # With λ = 0.1  & δ = 1e-8
    λ = 0.1
    δ = 1e-8

    xopt = optimize(S.C[2], W, λ, δ)

    @test norm(xopt -[0.353742957402480; -0.512879943932609; 1.411791355362390 ])<1e-10
end

@testset "Test optimization for Nx=3 and p=0" begin

   Nx = 3
   Ne = 10
   p = 0
   γ = 2.0

   X = Matrix([0.1733    0.2760    1.0093; 0.6163    0.4598  0.0510;0.8639   -0.2175   -0.4404;-1.4169    0.7961   -0.8485;0.2000   -1.5180   -0.2404;0.1958   -1.0749    0.6029;-0.1511   -3.0722   -1.5163;0.8928    0.5214   -0.0683;-0.3642   -0.9910    0.7824;-0.8262   -0.2531   -1.4207]')
   S = RadialMap(Nx, p; γ = γ)
   center_std!(S, X)
   W = create_weights(S, X)
  compute_weights(S, X, W)

   # With λ = δ = 0.0
   λ = 0.0
   δ = 0.0

   xopt = optimize(S.C[3], W, λ, δ)

   @test norm(xopt -[-0.609710825728394; -0.275729138896713; 0.156805424543943; 1.366651306860556])<1e-10

   # With λ = 0.1  & δ = 1e-8
   λ = 0.1
   δ = 1e-8

   xopt = optimize(S.C[3], W, λ, δ)

   @test norm(xopt -[-0.603717368357810; -0.273039744501052; 0.158055928017947; 1.366632953261741])<1e-10

end


@testset "Test optimization for Nx=1 and p=3" begin
   Nx = 1
   Ne = 10
   p = 3
   γ = 2.0

   X = reshape([-1.5438
      -1.5518
       0.8671
      -0.1454
      -0.3862
       1.3162
      -0.7965
       0.1354
       0.4178
       0.8199],1,Ne)


   S = RadialMap(Nx, p; γ = γ)
   W = create_weights(S, X)
   center_std!(S, X)
  compute_weights(S, X, W)

   # With λ = δ = 0.0
   λ = 0.0
   δ = 0.0
   xopt = optimize(S.C[1], W, λ, δ);

   @test norm(xopt - [0.453363732161572; 2.304194295945015; 0.0; 0.0; 0.0;2.552281803302206])<1e-10


   # With λ = 0.1 and δ = 1e-8
   λ = 0.1
   δ = 1e-8
   xopt = optimize(S.C[1], W, λ, δ);

   @test norm(xopt - [0.450882345511096; 2.295315495868833; 0.000000043115815; 0.000000032750391; 0.000000035316480; 2.547661799360081])<1e-10

end

@testset "Test optimization for Nx=2 and p=2" begin

    Nx = 2
    Ne = 10
    p = 2
    γ = 2.0
    λ = 0.0

    X = Matrix([-0.8544   -0.7938;0.3573    0.5410;
                2.7485   -0.5591; -1.5130    1.9766;
                0.4340    0.5447; -0.2298   -0.1379;
                 -0.8271   0.6199;-0.8320   -0.0056;
                  0.4979    1.1072;2.3156   -0.1856]')

    @time S = RadialMap(Nx, p; γ = γ)

    center_std!(S, X);

    W = create_weights(S, X)
   compute_weights(S, X, W)
    λ = 0.0
    δ = 0.0

    ψ_off, ψ_mono, dψ_mono = rearrange(W,2)

    @test norm(ψ_off -[-0.854400000000000   0.156738618846197   0.137603564500746;
       0.357300000000000   0.140640215047531   0.156654816189471;
       2.748500000000000   0.058401570295014   0.104057315307723;
      -1.513000000000000   0.151170210915668   0.116608188942393;
       0.434000000000000   0.138617339050529   0.156745732145583;
      -0.229800000000000   0.152477989231576   0.151338989275322;
      -0.827100000000000   0.156747096365829   0.138351021862248;
      -0.832000000000000   0.156746902701754   0.138217735507039;
       0.497900000000000   0.136859341544330   0.156712800799488;
       2.315600000000000   0.073104270826721   0.119634493493623])<1e-10


    @test norm(ψ_mono -[-0.507201580119279   0.215069670075122   0.076485784936572   0.000988033380379;
      -0.016861853328784   0.748419931509968   0.499210902664930   0.126296856325961;
      -0.344698250357007   0.297187601194573   0.119362800788456   0.002977317564677;
      -0.000006458746850   0.987394188705160   0.937353523618463   1.123806421603995;
      -0.016625169238807   0.749707195139661   0.500789097335070   0.127438446122333;
      -0.140628787073782   0.471189825582940   0.233355359282062   0.016320116571698;
      -0.012393614690139   0.775096387582616   0.532827724212160   0.152299949965802;
      -0.099762356857753   0.528810174417060   0.278806935049185   0.025944471088712;
      -0.001358786238840   0.901159801018090   0.726875126285091   0.395949949965802;
      -0.157948250357007   0.450499667316035   0.218036687265869   0.013696473624777])<1e-10

      @test norm(dψ_mono -[0.758353059754083   0.319323853074808   0.153626107072438   0.004883698987942
       0.064354624108671   0.348381106647456   0.426538543776643   0.307522804512740
       0.621958562984279   0.378284965307517   0.213076838459543   0.013276098094082
       0.000046704774842   0.035615595830791   0.131731605768779   0.958660103131430
       0.063583925230259   0.347436551236228   0.426538543776643   0.309553737400797
       0.348279343219786   0.434770043962370   0.327283964601450   0.059220575922185
       0.049425557686157   0.327622035258933   0.425094484357949   0.352020159021600
       0.270920987266371   0.434770043962370   0.359163756509705   0.087695615816903
       0.006927621078729   0.190131276118064   0.355549818399670   0.647979840978400
       0.378041437015721   0.432547368859386   0.314948152204838   0.050949232751226])<1e-10

    # Rescale variable

    ψ_off, ψ_mono, dψ_mono = rearrange(W,2)

    no = size(ψ_off,2)
    nd = size(ψ_mono,2)
    nx = size(ψ_off,2)+size(ψ_mono,2)+1
    nlog = size(dψ_mono,2)

    x = zeros(nx)

    μψ = deepcopy(mean(ψ_mono, dims=1)[1,:])
    σψ = deepcopy(std(ψ_mono, dims=1, corrected=false)[1,:])

    ψ_mono .-= μψ'
    ψ_mono ./= σψ'
    dψ_mono ./= σψ'

    A = ψ_mono'*ψ_mono
    rmul!(A,1/Ne)

    μψ_off = deepcopy(mean(ψ_off, dims = 1)[1,:])
    σψ_off = deepcopy(std(ψ_off, dims = 1, corrected = false)[1,:])
    ψ_off .-= μψ_off'
    ψ_off ./= σψ_off'

    # Verify that ψ_off, ψ_mono and dψ_mono are correctly rescaled
    @test norm(ψ_off -[ -0.804643054198426   0.720356396590189   0.000623052929297;
       0.111611046705843   0.248725359467419   1.070112263485765;
       1.919770497132754  -2.160600297987687  -1.882578752010958;
      -1.302658198917046   0.557220098094831  -1.178004367363986;
       0.169609470027917   0.189461651315464   1.075216055914641;
      -0.332337771187114   0.595533762677487   0.771695150386939;
      -0.783999547592264   0.720604760429600   0.042583423646065;
      -0.787704792367729   0.720599086700126   0.035101063896698;
       0.217928886589593   0.137958024156060   1.073367373218454;
       1.592423463806471  -1.729858841443491  -1.008115264102931])<1e-10

    @test norm(ψ_mono -[-2.326960601058417  -1.624755258466316  -1.277802709623370  -0.600690875072745;
       0.695935005892621   0.555916671737632   0.330653865772685  -0.219729086471929;
      -1.325143748753542  -1.289005413932899  -1.114656931934708  -0.594643086552582;
       0.799846835694096   1.532994011692314   1.997773585133276   2.812882817478138;
       0.697394139747648   0.561179816554494   0.336658849834394  -0.216258444258148;
      -0.067075820810003  -0.577574682660793  -0.680918616973539  -0.554078532076930;
       0.723481252328697   0.664986832870473   0.458564877903041  -0.140674915908932;
       0.184861653602686  -0.341986390319673  -0.507976714922384  -0.524818730374682;
       0.791509871317472   1.180413498950799   1.196909505920374   0.600065740739791;
      -0.173848587961260  -0.662169086426033  -0.739205711109769  -0.562054887501982])<1e-10

    @test norm(dψ_mono -[4.675171126462628   1.305597115808049   0.584542795566616   0.014847340017250;
       0.396739851731833   1.424401477250050   1.622966548768615   0.934925689100038;
       3.834312630667317   1.546667293731231   0.810751070876959   0.040361771475244;
       0.000287930287880   0.145618996973497   0.501234865401183   2.914502418618957;
       0.391988569862249   1.420539539569087   1.622966548768615   0.941100097313083;
       2.147107483013941   1.777613886251173   1.245305809396379   0.180041404866467;
       0.304703643285317   1.339525313221805   1.617471945373052   1.070205802369169;
       1.670200918858584   1.777613886251173   1.366607475104451   0.266610745107435;
       0.042708094370782   0.777376457581746   1.352856547439218   1.969977479587423;
       2.330587828729104   1.768526189933186   1.198368407926584   0.154895005638792])<1e-10


    # Verify that we get the same QR decomposition
    #Assemble reduced QR to solve least square problem
    F = qr(vcat(ψ_off, Matrix(√λ*I, no, no)))
    Q1 = F.Q[1:Ne,1:no]
    Asqrt = ψ_mono - Q1*(Q1'*ψ_mono)
    # A = (Asqrt*Asqrt')/Ne
    A = BLAS.gemm('T', 'N', 1/Ne, Asqrt, Asqrt)

    @test norm(Q1 - [ -0.254450475470134   0.038542438904502  -0.287807026572883;
       0.035294511962590  -0.342003510157944   0.197040760785064;
       0.607084735573325   0.334774229448390  -0.420694384780400;
      -0.411936692127055   0.650442320408613   0.454822398694172;
       0.053635223802228  -0.337693395873161   0.262404719972692;
      -0.105094430945516  -0.271842813033772  -0.232724768964479;
      -0.247922425493313   0.019468149870942  -0.298845707008466;
      -0.249094126771204   0.022854173498846  -0.296968816757815;
       0.068915164956764  -0.332045729496864   0.316658455434137;
       0.503568514512315   0.217504136430448   0.306114369197955])<1e-10

    @test norm(Asqrt - [ -1.950781401302997  -1.300838981851897  -0.991890513984422  -0.458060391024002;
       0.099892510115221   0.085352068075599   0.033990870033547  -0.016912053174583;
       0.149656589279390   0.450550985993256   0.548653802955680   0.551333139636105;
       0.144073370024957   0.204556328914631   0.251633283508030   0.327703732540707;
      -0.003122789715729  -0.027881050368865  -0.081782795321125  -0.121731102269892;
       0.083258235300422  -0.268551915835203  -0.230658522708182   0.178298456149084;
       1.110570901959247   1.016081154773970   0.783074186747397   0.062561590138456;
       0.570158295426148   0.004447219686410  -0.190152589533267  -0.332197943172162;
       0.005871968596686   0.493585572789772   0.676896851023931   0.601539422000769;
      -0.209577679683306  -0.657301382177627  -0.799764572721539  -0.792534850824440])<1e-10

    @test norm(A - [0.546802799943131   0.389242527702498   0.297060133111796   0.108653878210649;
       0.389242527702498   0.372531651490579   0.331069886098672   0.174530422370543;
       0.297060133111796   0.331069886098672   0.315641016351602   0.196073264491252;
       0.108653878210649   0.174530422370543   0.196073264491252   0.177230269927555])<1e-10


    # Solve nonlinear optimization problem for g_mono
    g_mono = ones(nd)
    # Construct loss function, the convention is flipped inside the solver
    lhd = LHD(A, dψ_mono, λ, δ)
    g_mono,_,_,_ = projected_newton(g_mono, lhd, "TrueHessian")

    g_mono .+= δ

    @test norm(g_mono - [0.586712518793935; 0.421099709077361; 0; 1.154877772114433] )<1e-10

    # Approximate off-diagonal components
    @test norm(F.R -[3.162277660168379  -2.987894843243091  -1.096427127338353;
                      0  -1.035608229844348  -2.909339089462357;
                      0                   0   0.577575637438866])<1e-10

    g_off = -F.R\(Q1'*(ψ_mono*g_mono))

    @test norm(g_off -   [18.950658982438039; 21.898788492005636;-7.359525277156965])<1e-10

    g_mono ./= σψ
    g_off ./= σψ_off

    @test norm(g_mono - [3.617024276646359; 1.721720943628389; 0; 3.511040095485572] )<1e-10

    @test norm(g_off - 100*[ 0.143299653441423; 6.415635026543544; -4.131451837044035])<1e-10

    x[no+1] = -dot(μψ, g_mono)-dot(μψ_off, g_off)

    @test norm(x[no+1] -(-32.224538086041441))<1e-10

    x[no+2:nx] .= deepcopy(g_mono)


    if Nx>1
    x[1:no] .= deepcopy(g_off)
    end


    @test norm(x - [  14.32996534414215; 641.5635026543499; -413.14518370440067; -32.22453808604119; 3.61702427664633; 1.721720943628398; 0.0; 3.511040095485544])<1e-10

     xopt = optimize(S.C[2], W, λ, δ);
     @test norm(xopt - [  14.32996534414215; 641.5635026543499; -413.14518370440067; -32.22453808604119; 3.61702427664633; 1.721720943628398; 0.0; 3.511040095485544])<1e-10



       # With λ=0.1 and δ =1e-8
       λ = 0.1
       δ = 1e-8
       xopt = optimize(S.C[2], W, λ, δ);
       @test norm(xopt - [  1.765903393601119; 67.455814562648044; -48.756672231027366;  -3.584068900212547; 2.685855024209524; 1.468924592466743; 0.477896050052401; 1.308323191869906])<1e-10


 end

 @testset "Test optimization for Nx=2 and p=3" begin
     Nx = 2
     Ne = 10
     p = 3
     γ = 2.0

     X = Matrix([ -0.8544   -0.7938;0.3573    0.5410;
       2.7485   -0.5591; -1.5130    1.9766;
       0.4340    0.5447; -0.2298   -0.1379;
        -0.8271   0.6199;-0.8320   -0.0056;
         0.4979    1.1072;2.3156   -0.1856]')

     S = RadialMap(Nx, p; γ = γ)

     center_std!(S, X);

     W = create_weights(S, X)
    compute_weights(S, X, W)


     # With λ = δ = 0.0
     λ = 0.0
     δ = 0.0

     xopt = optimize(S.C[2], W, λ, δ);
     @test norm(xopt - [100*0.090840649611966; 100*1.373434239444840; 100*0.414826633064425; 100*(-0.287690260374867); -29.015187078639887; 4.209897756012423; 0.108369156771108; 0; 0; 8.850495668947518])<1e-10


     # With λ = 0.1 and δ = 1e-8
     λ = 0.1
     δ = 1e-8

     xopt = optimize(S.C[2], W, λ, δ);
     @test norm(xopt - [3.855369324206674; 28.717863158966477; 49.828564728403187; -23.158217471101509; -12.460695228234130; 3.669743272444025; 0.000000038099920; 0.794735311810544; 0.486353838959244; 5.376840166095511])<1e-10
 end


 @testset "Test optimization for Nx=3 and p=3" begin

     Nx = 3
     Ne = 10
     p = 3
     γ = 2.0

     X = Matrix([0.1733    0.2760    1.0093;
                   0.6163    0.4598  0.0510;
                 0.8639   -0.2175   -0.4404;
                -1.4169    0.7961   -0.8485;
                 0.2000   -1.5180   -0.2404;
                 0.1958   -1.0749    0.6029;
                -0.1511   -3.0722   -1.5163;
                 0.8928    0.5214   -0.0683;
                -0.3642   -0.9910    0.7824;
                -0.8262   -0.2531   -1.4207]')

     @time S = RadialMap(Nx, p; γ = γ)

     center_std!(S, X);
     W = create_weights(S, X)
    compute_weights(S, X, W)


     # With λ = δ = 0.0
     λ = 0.0
     δ = 0.0

     xopt = optimize(S.C[3], W, λ, δ);
     x_matlab  = [0.002236347046586e5;
     0.825719944026571e5    ;
     -1.071956974125768e5    ;
     0.593296179017564e5    ;
     -0.011049031761152e5    ;
     0.833628110516284e5      ;
     -1.085535253851930e5       ;
     0.696061056463158e5      ;
     -1.562689086584463e+04 ;
           0.0             ;
           0.0             ;
           0.0             ;
           0.0             ;
           1000*2.263679644184734  ]
     @test norm(xopt - x_matlab)/norm(x_matlab)<1e-10


     # With λ = 0.1 and δ = 1e-8
     λ = 0.1
     δ = 1e-8
     #
     xopt = optimize(S.C[3], W, λ, δ);

     @test norm(xopt - [   1.051136807671425;
     0.638509720542414;
     -23.285653280072371;
     -0.955334980052370;
     -2.821327423813651;
     -15.674943048773969;
     5.749217387570198;
     13.386252213401695;
     6.134578583234069;
     5.778639058642066;
     0.000000041429348;
     0.000000029234255;
     0.000000036290793;
     3.914178426750072])<1e-10
 end

In [34]:
Nx = 5
Ne = 100

X = randn(Nx, Ne) .* randn(Nx, Ne)

λ = 0.0
δ = 1e-8
γ = 2.0

2.0

In [3]:
@time Cgreedy = greedyfit(Nx, 2, X, 3, λ, δ, γ)

size(F) = (3, 100)


LoadError: DimensionMismatch("for a right-sided multiplication, the second dimension of C, 4, must equal the second dimension of A, 3")

In [23]:
# using BenchmarkTools
N = 200
nx = 597
λ = 0.0

ψ = rand(nx,N)
ψ_aug = zeros(N+nx, nx)

ψ_aug[1:N,:] .= ψ'
ψ_aug[N+1:N+nx,:] .= Matrix(sqrt(λ)*I, nx, nx)

F = qr(ψ_aug)

Q1 = zeros(N, nx)
Q1 .= view(F.Q*Matrix(I, N+nx, N+nx), 1:N, 1:nx)
Q1 .= (F.Q*Matrix(I,N+nx, N+nx))[1:N, 1:nx]
Q1 .= Matrix{Float64}(F.Q)[1:N, 1:nx];


ψbis  = rand(4, N) 

A = ψbis - (ψbis*Q1)*Q1';

In [24]:
F = qr(ψ')
size(F)

(200, 597)

In [21]:
ψbis

4×200 Array{Float64,2}:
 0.629605   0.326684  0.874646   0.0411056  …  0.363469  0.317491  0.934818
 0.22399    0.283091  0.53219    0.4247        0.527785  0.164593  0.871868
 0.566864   0.511157  0.700122   0.348717      0.723372  0.334182  0.952003
 0.0505716  0.995667  0.0391326  0.143356      0.769447  0.401063  0.300964

In [33]:
Matrix(qr(ψ_aug).Q)[1:200, 1:200]-Matrix(F.Q)

200×200 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …   1.94289e-16   7.04298e-16
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -6.80012e-16  -2.498e-16
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      1.66533e-16  -1.39472e-15
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -5.44703e-16  -4.28477e-16
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      4.60569e-16  -5.55112e-17
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …   3.46945e-17  -4.15466e-16
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -3.48679e-16  -3.46945e-17
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      4.19803e-16   6.93889e-18
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -7.21645e-16   1.08247e-15
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      3.67761e-16   1.38778e-16
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …   4.0766e-16    1.52656e-16
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -9.36751e-16  -1.11022e-16
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     -1.17961e-16   

In [30]:
Matrix(F.Q)

200×200 Array{Float64,2}:
 -0.0484646     0.00365827   0.0430735   …  -0.149698     0.023572
 -0.112344     -0.0339007    0.12418         0.0304372   -0.0260589
 -0.0447021     0.0304689   -0.0561091       0.171499     0.0426105
 -0.00403244   -0.0666002   -0.102289        0.0212374   -0.00875819
 -0.0509554     0.0016974    0.0248697      -0.00401667  -0.0389847
 -0.016677     -0.0124505   -0.0953902   …  -0.0280913   -0.00500914
 -0.0632723    -0.0343341    0.0449113       4.77836e-5   0.00135624
 -0.0183401     0.019794    -0.0860882      -0.0133249    0.0187791
 -0.0889232     0.0664824   -0.086204       -0.102532    -0.100871
 -0.019835     -0.0276584    0.0344452      -0.0465461    0.107352
 -0.000194863  -0.147459     0.0629499   …   0.0112554   -0.0544895
 -0.128356      0.0768003   -0.0981032       0.0149366   -0.112761
 -0.0391227    -0.10365      0.0158012      -0.041985    -0.0089801
  ⋮                                      ⋱               
 -0.0154384    -0.0936191    0.04

In [10]:
Q1 = zeros(N, nx)

200×597 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.

In [15]:
ψbis

4×200 Array{Float64,2}:
 0.629605   0.326684  0.874646   0.0411056  …  0.363469  0.317491  0.934818
 0.22399    0.283091  0.53219    0.4247        0.527785  0.164593  0.871868
 0.566864   0.511157  0.700122   0.348717      0.723372  0.334182  0.952003
 0.0505716  0.995667  0.0391326  0.143356      0.769447  0.401063  0.300964

In [20]:
F.Q'*(F.Q*ψbis')

┌ Error: Failed to revise /media/mat/HDD/AdaptiveTransportMap/src/radialmap/greedyfit.jl
│   exception = (InterruptException(), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007efdf81ec367, Ptr{Nothing} @0x00007efdf81f1bf6, Ptr{Nothing} @0x00007efdf816fc0e, Ptr{Nothing} @0x00007efdf8173597, Ptr{Nothing} @0x00007efdbcf54771])
└ @ Revise /home/mat/.julia/packages/Revise/AIcio/src/packagedef.jl:709
┌ Warning: The running code does not match the saved version for the following files:
│ 
│   /media/mat/HDD/AdaptiveTransportMap/src/radialmap/greedyfit.jl
│ 
│ If the error was due to evaluation order, it can sometimes be resolved by calling `Revise.retry()`.
│ Use Revise.errors() to report errors again. Only the first error in each file is shown.
│ Your prompt color may be yellow until the errors are resolved.
└ @ Revise /home/mat/.julia/packages/Revise/AIcio/src/packagedef.jl:805


200×4 Array{Float64,2}:
 0.629605   0.22399     0.566864  0.0505716
 0.326684   0.283091    0.511157  0.995667
 0.874646   0.53219     0.700122  0.0391326
 0.0411056  0.4247      0.348717  0.143356
 0.613903   0.632356    0.325746  0.514586
 0.902662   0.328683    0.525948  0.842128
 0.98988    0.169419    0.476712  0.805326
 0.540091   0.635358    0.622532  0.570431
 0.814644   0.160029    0.252947  0.960906
 0.718986   0.192323    0.140789  0.801022
 0.304391   0.534458    0.226681  0.085667
 0.948703   0.749022    0.898236  0.337926
 0.99419    0.911562    0.932376  0.711603
 ⋮                                
 0.194676   0.53485     0.209457  0.452462
 0.590701   0.250214    0.258469  0.0182
 0.0722457  0.983296    0.896947  0.303564
 0.406428   0.338016    0.288047  0.523898
 0.860231   0.941426    0.232003  0.297934
 0.0754768  0.00051333  0.485187  0.265898
 0.668773   0.158696    0.60858   0.0370232
 0.715556   0.586149    0.585833  0.582811
 0.77708    0.747355    0.471161  0.8

In [42]:
F = qrfactUnblocked(zeros(0,0))

QR{Float64,Array{Float64,2}}
Q factor:
0×0 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}
R factor:
0×0 Array{Float64,2}

In [39]:
push!(tmp, zeros(5))

LoadError: MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Float64
Closest candidates are:
  convert(::Type{T}, ::Static.StaticInt{N}) where {T<:Number, N} at /home/mat/.julia/packages/Static/BGJW6/src/static_implementation.jl:22
  convert(::Type{T}, ::Static.StaticFloat64{N}) where {N, T<:AbstractFloat} at /home/mat/.julia/packages/Static/BGJW6/src/float.jl:26
  convert(::Type{T}, ::VectorizationBase.LazyMulAdd{M,O,I}) where {M, O, I, T<:Number} at /home/mat/.julia/packages/VectorizationBase/4k8ZW/src/lazymul.jl:17
  ...

In [40]:
p = 2
order = p*ones(Int64, Nx)
order[1] = p
order[end] = p

order = [p; p; -1; p; p]

C = SparseRadialMapComponent(Nx, order)
center_std!(C, sort(X; dims = 2); γ = γ)

@time xdiag = optimize(C, X, λ, δ)
modify_a!(C, xdiag)

  0.000746 seconds (5.15 k allocations: 695.750 KiB)


In [42]:
    # Compute centers and widths
    center_std!(C, sort(X; dims = 2); γ = γ)

    ### Evaluate the different basis

    # Create weights
    ψ_off, ψ_diag, dψ_diag = compute_weights(C, X);

In [43]:
ψ_off

9×100 Array{Float64,2}:
 -1.8943      0.524572  -0.377613  -0.0761536  …   0.384642  -3.25978
  0.0948513   0.291842   0.433812   0.423307       0.33072    0.00231141
  0.0349627   0.402897   0.365975   0.420995       0.42299    0.0004043
  0.093796    0.158934   0.980648   1.46379       -0.853686   0.210463
  0.386148    0.375565   0.178475   0.0819955      0.344625   0.366209
  0.411406    0.413904   0.301441   0.178004   …   0.224426   0.414543
  0.384716   -0.228189   0.595606  -1.6628        -0.711736  -0.0878159
  0.404086    0.534755   0.31367    0.0726118      0.413267   0.532475
  0.519375    0.455307   0.46454    0.023578       0.254256   0.49821

In [56]:
@time F.Q*(F.Q'*ψ_diag')

  0.000079 seconds (10 allocations: 7.391 KiB)


100×4 Array{Float64,2}:
 -0.00707087  0.924713    0.738385     0.37348
 -5.24541e-7  0.999992    0.993738     1.30523
 -0.0608338   0.62681     0.467749     0.18046
 -0.0969348   0.505746    0.389569     0.143246
 -0.112763    0.462505    0.362976     0.131668
 -0.891696    0.00621773  0.0284838    0.0128753
 -0.0484145   0.678355    0.503694     0.199457
 -0.0676156   0.601149    0.450559     0.171827
 -0.367903    0.122654    0.149201     0.0524203
 -0.169119    0.340947    0.28966      0.102052
 -0.0627705   0.619319    0.462688     0.177889
 -0.107679    0.475863    0.371142     0.135171
 -0.157954    0.361737    0.302165     0.106887
  ⋮                                    
 -0.00738085  0.922004    0.734416     0.369397
 -0.088528    0.530854    0.405258     0.150316
 -0.0744019   0.576978    0.434716     0.164108
 -0.198409    0.292461    0.260307     0.0910113
 -0.149867    0.377701    0.311757     0.110653
 -0.0496635   0.672873    0.499767     0.197315
 -0.0213552   0.819936  

In [52]:
Matrix(F.Q')[1:Ne,:]*ψ_diag'

100×4 Array{Float64,2}:
  0.259283   -1.26526     -1.14093    -1.10693
  2.43358    -4.98023     -4.15672    -3.03175
 -0.113712    1.00018      0.839181    0.0215528
  0.238057    0.185024     0.180396    0.246032
 -0.527554   -1.92636     -1.58001    -1.23033
 -0.0281731  -0.576664    -0.454201   -0.117531
  0.0324086   0.258376     0.112765   -0.40009
  0.999858   -0.360184    -0.288807    0.0484478
  0.189334   -0.356912    -0.284213   -0.163268
  0.168473    0.0464709    0.0292691  -0.050503
  0.324687    0.0042863   -0.0607825  -0.230189
  0.0883382   0.0648405    0.0460566   0.0261449
  0.0130686  -0.0570624   -0.0624704  -0.312733
  ⋮                                   
  0.236156    0.155029     0.0823092  -0.185805
  0.060593   -0.00593668  -0.0453959  -0.131984
  0.132133    0.524442     0.388536    0.193398
  0.0585351  -0.425783    -0.352708   -0.397807
  0.109684   -0.0136371   -0.0583209  -0.322824
  0.190798    0.189964     0.0581992  -0.237499
  0.185859    0.0863229   

In [44]:
F = qr(ψ_off')

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
100×100 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.17235     -0.0123195   0.0195756   …   0.0552232   -0.342795
  0.0477271   -0.090474    0.140895       -0.131694     0.00507162
 -0.0343564   -0.124909   -0.0934567       0.143054     0.15335
 -0.00692869  -0.124303   -0.00655872      0.0112888   -0.0174998
  0.0110816   -0.116911    0.05368        -0.08452     -0.0441607
  0.039191    -0.0974732   0.127091    …   0.129849    -0.180872
 -0.00775866  -0.124519   -0.00939141     -0.131624     0.0209253
  0.181403    -0.0221591  -0.0599955       0.0374523    0.0550513
 -0.133454    -0.0445787  -0.0776178       0.0188524    0.047145
  0.0575559   -0.0822022   0.150916       -0.0249855   -0.0082464
 -0.00117364  -0.122488    0.0130785   …   0.00616488  -0.0233737
  0.13222     -0.0328142   0.0549326       0.0011328    0.00471768
 -0.0266938   -0.126127   -0.0713438      -0.0067487   -0.0146783
  ⋮                  

In [159]:
@testset "Verify updateqrfactUnblocked! for a vector" begin

    ψ = randn(100, 20)
    ϕ = randn(100)

    F = qrfactUnblocked(ψ)
    Fold = deepcopy(F)
    G = qrfactUnblocked(hcat(ψ, ϕ))
    F = updateqrfactUnblocked!(F, ϕ)
    @test norm(F.τ-G.τ)<1e-14
    @test norm(F.factors - G.factors)<1e-14
end

@testset "Verify updateqrfactUnblocked! for a matrix" begin

    ψ = randn(100, 20)
    ϕ = randn(100, 5)

    F = qrfactUnblocked(ψ)
    Fold = deepcopy(F)
    G = qrfactUnblocked(hcat(ψ, ϕ))
    F = updateqrfactUnblocked!(F, ϕ)
    @test norm(F.τ-G.τ)<1e-14
    @test norm(F.factors - G.factors)<1e-14
end

Test Summary:                              | Pass  Total
Verify updateqrfactUnblocked! for a vector |    2      2
Test Summary:                              | Pass  Total
Verify updateqrfactUnblocked! for a matrix |    2      2


Test.DefaultTestSet("Verify updateqrfactUnblocked! for a matrix", Any[], 2, false)